import { useState } from "react";
import { AdminPageHeader } from "./ui/AdminPageHeader";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Copy, Check, Wifi, WifiOff, Loader2, Download, Upload } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import stableBridgeFiles from "@/data/bridge-files-stable.json";

// ─── Stable bundle (manifest) — generated by scripts/build-stable-bundle.mjs ───
// Contains BOTH the 5 runtime files AND deploy-agent.ts. Do NOT ship the
// whole manifest to /deploy — filter to RUNTIME_DEPLOY_FILES first.
const STABLE_DEPLOY_FILES: Record<string, string> = stableBridgeFiles;

// Explicit runtime allowlist. Mirrors RUNTIME_FILES in build-stable-bundle.mjs
// and the VPS deploy-agent's hardcoded whitelist. Used for both:
//   1. The "Deploy stable bridge" payload (only these 5 files are POSTed).
//   2. The displayed BUILD_VERSION + fingerprint (must match what the bridge
//      reports at boot, which is hashed over runtime files only).
const RUNTIME_FILE_NAMES = [
  "server.ts",
  "gemini-session.ts",
  "supabase-logger.ts",
  "config.ts",
  "transcript-persist.ts",
] as const;
const RUNTIME_DEPLOY_FILES: Record<string, string> = Object.fromEntries(
  RUNTIME_FILE_NAMES
    .filter((n) => n in STABLE_DEPLOY_FILES)
    .map((n) => [n, STABLE_DEPLOY_FILES[n]]),
);

function extractBuildVersion(files: Record<string, string>): string {
  for (const content of Object.values(files)) {
    const m = content.match(/BUILD_VERSION\s*=\s*["']([^"']+)["']/);
    if (m) return m[1];
  }
  return "unknown";
}

// Read the embedded BUNDLE_HASH that scripts/build-stable-bundle.mjs writes
// into supabase-logger.ts. This is the SAME value the bridge reports at
// /health.bundle_hash, so the admin UI label and /health are directly
// comparable. Do NOT recompute a local hash for display — the canonical
// form must match what the bridge actually publishes at runtime.
function extractBundleHash(files: Record<string, string>): string {
  for (const content of Object.values(files)) {
    const m = content.match(/BUNDLE_HASH\s*=\s*["']([^"']+)["']/);
    if (m) return m[1];
  }
  return "unknown";
}

const STABLE_BUILD_VERSION = extractBuildVersion(RUNTIME_DEPLOY_FILES);
const STABLE_BUNDLE_HASH = extractBundleHash(RUNTIME_DEPLOY_FILES);
const STABLE_FILE_COUNT = Object.keys(RUNTIME_DEPLOY_FILES).length;
const EXTRA_FILE_COUNT = Object.keys(STABLE_DEPLOY_FILES).length - STABLE_FILE_COUNT;

const ENV_TEMPLATE = `# Gemini Bridge Environment Variables
# Copy this to /opt/gemini-bridge/.env

# Google Cloud API Key (Gemini API access)
GOOGLE_CLOUD_API_KEY=your-google-api-key-here

# Supabase connection
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here

# Voice configuration
GEMINI_VOICE=Aoede
PORT=3100

# Bridge external URL (used by listen verb to connect back for audio)
# If Jambonz is on the SAME server: ws://localhost:3100
# If Jambonz is on a DIFFERENT server: ws://YOUR_VPS_IP:3100
BRIDGE_EXTERNAL_URL=ws://localhost:3100

# Optional: TLS (for wss://)
# TLS_CERT_PATH=/etc/letsencrypt/live/yourdomain/fullchain.pem
# TLS_KEY_PATH=/etc/letsencrypt/live/yourdomain/privkey.pem

# Optional: Escalation transfer
# ESCALATION_TRANSFER_NUMBER=+66xxxxxxxxx`;

const DEPLOY_GUIDE = `# Gemini Bridge Deployment Guide

## Prerequisites
- VPS with Ubuntu 22.04+ (Singapore/HK region recommended for low latency)
- Root/sudo access
- Firewall access to open port 3100

## Step 1: Install Deno

curl -fsSL https://deno.land/install.sh | sh
echo 'export DENO_INSTALL="$HOME/.deno"' >> ~/.bashrc
echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
deno --version

## Step 2: Create project directory

sudo mkdir -p /opt/gemini-bridge
sudo chown $USER:$USER /opt/gemini-bridge

## Step 3: Copy bridge files

For the safest rollback, copy these core bridge files to /opt/gemini-bridge/:
- server.ts
- config.ts
- gemini-session.ts
- supabase-logger.ts

Optional after the bridge is healthy again:
- deploy-agent.ts   # restores one-click "Deploy to VPS" on port 3101
- bridge-logger.ts  # remote bridge logs in the admin UI

## Step 4: Create .env file

cp .env.template /opt/gemini-bridge/.env
nano /opt/gemini-bridge/.env
# Fill in your actual values
# IMPORTANT: Set BRIDGE_EXTERNAL_URL appropriately:
#   Same server as Jambonz: ws://localhost:3100
#   Different server: ws://YOUR_VPS_IP:3100

## Step 5: Create systemd service

sudo tee /etc/systemd/system/gemini-bridge.service << 'EOF'
[Unit]
Description=Gemini Voice Bridge
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/gemini-bridge
EnvironmentFile=/opt/gemini-bridge/.env
ExecStart=/root/.deno/bin/deno run --allow-net --allow-env --allow-read server.ts
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

## Step 6: Enable and start

sudo systemctl daemon-reload
sudo systemctl enable gemini-bridge
sudo systemctl start gemini-bridge
sudo systemctl status gemini-bridge

## Step 7: Verify

curl http://localhost:3100/health
# Should return: {"status":"ok","activeCalls":0,"uptime":...}

## Step 8: Configure firewall

sudo ufw allow 3100/tcp
# Also allow RTP if needed:
sudo ufw allow 40000:60000/udp

## Step 9: Configure Jambonz

In the Jambonz portal:
1. Create/edit your Application
2. Set WebSocket URL: ws://YOUR_VPS_IP:3100
   (This is the ROOT path — the bridge handles session:new here
    and responds with a listen verb pointing to /audio)
3. Audio format: L16 PCM 16kHz mono
4. Assign a DID phone number to this application

## Architecture

Jambonz connects to ws://VPS:3100/ (root path):
  → Bridge receives session:new
  → Bridge responds with ack containing listen verb
  → listen verb URL points to ws://VPS:3100/audio?callSid=...&from=...&to=...
  → Jambonz opens second WebSocket to /audio for bidirectional audio
  → Bridge connects to Gemini and streams audio both ways

## Troubleshooting

# View logs
sudo journalctl -u gemini-bridge -f

# Restart
sudo systemctl restart gemini-bridge

# Check if port is listening
ss -tlnp | grep 3100

# Expected log flow on a call:
# [Bridge] New Jambonz app protocol connection
# [Bridge] Received message type: session:new
# [Bridge] Sending ack with listen verb → ws://localhost:3100/audio?callSid=...
# [Bridge] Audio connection for call ...
# [Bridge] Gemini ready for call ...`;

function CodeBlock({ code, filename }: { code: string; filename: string }) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    toast({ title: "Copied!", description: `${filename} copied to clipboard` });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative">
      <div className="flex items-center justify-between bg-[#1e1e1e] rounded-t-lg px-4 py-2">
        <span className="text-xs text-[#9CA3AF] font-mono">{filename}</span>
        <Button
          variant="ghost"
          size="sm"
          onClick={handleCopy}
          className="h-7 px-2 text-[#9CA3AF] hover:text-white hover:bg-white/10"
        >
          {copied ? <Check className="h-3.5 w-3.5 mr-1" /> : <Copy className="h-3.5 w-3.5 mr-1" />}
          <span className="text-xs">{copied ? "Copied" : "Copy"}</span>
        </Button>
      </div>
      <pre className="bg-[#1e1e1e] text-[#d4d4d4] p-4 rounded-b-lg overflow-x-auto text-xs font-mono leading-relaxed max-h-[600px] overflow-y-auto">
        <code>{code}</code>
      </pre>
    </div>
  );
}

async function saveTextFile(filename: string, content: string): Promise<"saved" | "downloaded" | "opened" | "cancelled"> {
  const blob = new Blob([content], { type: "text/x-shellscript;charset=utf-8" });
  const fileWindow = window as Window & {
    showSaveFilePicker?: (options?: {
      suggestedName?: string;
      types?: Array<{
        description?: string;
        accept: Record<string, string[]>;
      }>;
    }) => Promise<{
      createWritable: () => Promise<{
        write: (data: Blob) => Promise<void>;
        close: () => Promise<void>;
      }>;
    }>;
  };

  if (fileWindow.showSaveFilePicker) {
    try {
      const handle = await fileWindow.showSaveFilePicker({
        suggestedName: filename,
        types: [
          {
            description: "Shell script",
            accept: {
              "text/x-shellscript": [".sh"],
              "text/plain": [".sh"],
            },
          },
        ],
      });
      const writable = await handle.createWritable();
      await writable.write(blob);
      await writable.close();
      return "saved";
    } catch (error: any) {
      if (error?.name === "AbortError") return "cancelled";
    }
  }

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  const popup = window.open(url, "_blank", "noopener,noreferrer");
  setTimeout(() => URL.revokeObjectURL(url), 5000);
  return popup ? "opened" : "downloaded";
}

export function GeminiBridgeDeploy() {
  const { toast } = useToast();
  const [healthStatus, setHealthStatus] = useState<"idle" | "checking" | "ok" | "error">("idle");
  const [healthData, setHealthData] = useState<any>(null);
  const [bridgeUrl, setBridgeUrl] = useState("http://localhost:3100");
  const [deployStatus, setDeployStatus] = useState<"idle" | "deploying" | "success" | "error">("idle");
  const [deployError, setDeployError] = useState<string | null>(null);

  const downloadAllAsZip = async () => {
    const files = Object.entries(RUNTIME_DEPLOY_FILES).map(([name, content]) => ({
      name: `gemini-bridge/${name}`,
      content,
    }));
    files.push({ name: "gemini-bridge/.env.template", content: ENV_TEMPLATE });

    const script = files.map(({ name, content }) => {
      const path = name.replace("gemini-bridge/", "");
      return `cat > /opt/gemini-bridge/${path} << 'ENDOFFILE'\n${content}\nENDOFFILE`;
    }).join("\n\n");

    const fullScript = `#!/bin/bash
# Gemini Bridge Stable Installer (with inlined logs)
# Ships the 4 whitelisted files; live bridge logs are written via the
# logger inlined into supabase-logger.ts. Run: bash install-gemini-bridge.sh

set -e
mkdir -p /opt/gemini-bridge
echo "Creating Gemini Bridge files..."

${script}

echo ""
echo "✅ All files created in /opt/gemini-bridge/"
echo "Next steps:"
echo "  1. Edit /opt/gemini-bridge/.env.template → rename to .env and fill in your keys"
echo "  2. Run: cd /opt/gemini-bridge && deno run --allow-net --allow-env --allow-read server.ts"
`;

    const blob = new Blob([fullScript], { type: "text/x-shellscript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "install-gemini-bridge.sh";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    toast({ title: "Stable installer downloaded", description: "install-gemini-bridge.sh" });
  };

  const checkHealth = async () => {
    setHealthStatus("checking");
    try {
      const res = await fetch(`${bridgeUrl}/health`, { signal: AbortSignal.timeout(5000) });
      const data = await res.json();
      setHealthData(data);
      setHealthStatus("ok");
    } catch {
      setHealthStatus("error");
      setHealthData(null);
    }
  };

  const deployToVps = async () => {
    setDeployStatus("deploying");
    setDeployError(null);
    try {
      const { data, error } = await supabase.functions.invoke("deploy-bridge", {
        body: { files: RUNTIME_DEPLOY_FILES },
      });
      if (error) {
        const transportMsg = error.message?.includes("Failed to send")
          ? "Could not reach the deploy-bridge edge function. Verify DEPLOY_TOKEN and BRIDGE_DEPLOY_URL secrets are set, and that the VPS deploy agent at port 3101 is reachable from Supabase."
          : (error.message || "Edge function error");
        throw new Error(transportMsg);
      }
      if (data?.error) {
        if (data?.details?.deployAgentOutdated) {
          throw new Error(
            `${data.error}\n\nFix: SSH into the VPS and run the "Update Deploy Agent" script (download below).`,
          );
        }
        throw new Error(data.error);
      }
      setDeployStatus("success");
      toast({
        title: "Deployed!",
        description: `${data.deployed?.join(", ")} deployed and bridge restarted.`,
      });
      setTimeout(() => setDeployStatus("idle"), 5000);
    } catch (err: any) {
      setDeployStatus("error");
      setDeployError(err.message || "Deploy failed");
      toast({
        title: "Deploy failed",
        description: err.message || "Unknown error",
        variant: "destructive",
      });
    }
  };

  const remoteUpdateDeployAgent = async () => {
    const agentSrc = STABLE_DEPLOY_FILES["deploy-agent.ts"] || "";
    if (!agentSrc) {
      toast({
        title: "deploy-agent.ts missing from stable bundle",
        description:
          "Run `node scripts/build-stable-bundle.mjs` to regenerate src/data/bridge-files-stable.json.",
        variant: "destructive",
      });
      return;
    }
    try {
      // Compute sha256 in browser for end-to-end integrity check
      const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(agentSrc));
      const expected_sha256 = Array.from(new Uint8Array(buf))
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");

      toast({ title: "Updating deploy agent…", description: `Pushing ${agentSrc.length} bytes` });

      const { data, error } = await supabase.functions.invoke("deploy-bridge", {
        body: { action: "self_update_agent", agentSource: agentSrc, expected_sha256 },
      });
      if (error) throw new Error(error.message || "Edge function error");
      if (data?.error) throw new Error(data.error);

      toast({
        title: "Deploy agent updated",
        description: `sha256 ${String(data?.sha256 || "").slice(0, 16)}… Agent restarting; recheck health in ~5s.`,
      });
      setTimeout(() => { checkHealth(); }, 5000);
    } catch (err: any) {
      toast({
        title: "Self-update failed",
        description: err.message || "Unknown error. Use 'Download manual script' as a fallback.",
        variant: "destructive",
      });
    }
  };

  const downloadDeployAgentUpdater = async () => {
    const agentSrc = STABLE_DEPLOY_FILES["deploy-agent.ts"] || "";
    if (!agentSrc) {
      toast({
        title: "deploy-agent.ts missing from stable bundle",
        description:
          "Run `node scripts/build-stable-bundle.mjs` to regenerate src/data/bridge-files-stable.json.",
        variant: "destructive",
      });
      return;
    }
    const script = `#!/bin/bash
# Update Deploy Agent (manual fallback)
# Usage on the VPS (as root): bash update-deploy-agent.sh

set -e
echo "[1/4] Writing /opt/gemini-bridge/deploy-agent.ts ..."
mkdir -p /opt/gemini-bridge
cat > /opt/gemini-bridge/deploy-agent.ts <<'ENDOFAGENT'
${agentSrc}
ENDOFAGENT

echo "[2/4] Ensuring deploy-agent systemd service exists ..."
if ! systemctl list-unit-files | grep -q '^deploy-agent.service'; then
  cat > /etc/systemd/system/deploy-agent.service <<'EOF'
[Unit]
Description=Gemini Bridge Deploy Agent
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/gemini-bridge
EnvironmentFile=/opt/gemini-bridge/.env
ExecStart=/root/.deno/bin/deno run --allow-net --allow-env --allow-read --allow-write --allow-run deploy-agent.ts
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable deploy-agent
fi

echo "[3/4] Restarting deploy-agent ..."
systemctl restart deploy-agent

echo "[4/4] Health checks ..."
sleep 2
echo "--- deploy-agent (3101) ---"
curl -sS http://localhost:3101/health || true
echo ""
echo "--- gemini-bridge (3100) ---"
curl -sS http://localhost:3100/health || true
echo ""
echo "Done."
`;
    try {
      const saveResult = await saveTextFile("update-deploy-agent.sh", script);
      if (saveResult === "cancelled") return;

      toast({
        title: saveResult === "saved" ? "Manual script saved" : "Manual script ready",
        description:
          saveResult === "opened"
            ? `The script opened in a new tab because the browser did not place it in Downloads. Save it as update-deploy-agent.sh, then run it on the VPS as root.`
            : `update-deploy-agent.sh (${script.length} bytes). Run on the VPS as root: bash update-deploy-agent.sh`,
      });
    } catch (err: any) {
      toast({
        title: "Download failed",
        description: err?.message || "Browser blocked the download. Check pop-up/download permissions.",
        variant: "destructive",
      });
    }
  };

  return (
    <div>
      <AdminPageHeader
        title="Gemini Bridge Deployment"
        description="Voice AI bridge files, configuration, and deployment guide for Jambonz ↔ Gemini Live"
      />

      {/* Health Check Card */}
      <div className="bg-white border border-[#F3F0EB] rounded-xl p-4 mb-6">
        <div className="flex items-center gap-3 flex-wrap">
          <div className="flex items-center gap-2 flex-1 min-w-[200px]">
            <input
              type="text"
              value={bridgeUrl}
              onChange={(e) => setBridgeUrl(e.target.value)}
              placeholder="http://VPS_IP:3100"
              className="border border-[#E5E7EB] rounded-lg px-3 py-1.5 text-sm font-mono flex-1 bg-[#FAFAFA]"
            />
          </div>
          <Button onClick={downloadAllAsZip} variant="outline" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            Download Stable ZIP
          </Button>
          <Button onClick={remoteUpdateDeployAgent} variant="outline" size="sm" className="gap-2">
            <Upload className="h-4 w-4" />
            Update Deploy Agent
          </Button>
          <Button onClick={downloadDeployAgentUpdater} variant="ghost" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            Manual script
          </Button>
          <Button onClick={checkHealth} variant="outline" size="sm" className="gap-2">
            {healthStatus === "checking" ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : healthStatus === "ok" ? (
              <Wifi className="h-4 w-4 text-emerald-500" />
            ) : healthStatus === "error" ? (
              <WifiOff className="h-4 w-4 text-red-500" />
            ) : (
              <Wifi className="h-4 w-4" />
            )}
            Check Health
          </Button>
          <Button
            onClick={deployToVps}
            variant="default"
            size="sm"
            className="gap-2"
            disabled={deployStatus === "deploying"}
          >
            {deployStatus === "deploying" ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : deployStatus === "success" ? (
              <Check className="h-4 w-4" />
            ) : (
              <Upload className="h-4 w-4" />
            )}
            {deployStatus === "deploying" ? "Deploying..." : deployStatus === "success" ? "Deployed!" : "Deploy stable bridge"}
          </Button>
          {healthStatus === "ok" && healthData && (
            <div className="flex items-center gap-3 text-xs">
              <span className="flex items-center gap-1">
                <div className="w-2 h-2 rounded-full bg-emerald-500" />
                Online
              </span>
              <span className="text-muted-foreground">
                Active calls: {healthData.activeCalls} · Uptime: {Math.round(healthData.uptime / 60)}m
              </span>
            </div>
          )}
          {healthStatus === "error" && (
            <span className="text-xs text-destructive flex items-center gap-1">
              <div className="w-2 h-2 rounded-full bg-destructive" />
              Unreachable — the gemini-bridge process on the VPS is down or the URL is wrong. Use "Deploy stable bridge" to push the last known working bundle (now with live logs inlined), then update the deploy agent separately if needed.
            </span>
          )}
          {deployStatus === "error" && deployError && (
            <span className="text-xs text-destructive flex items-start gap-1 whitespace-pre-line max-w-full">
              Deploy error: {deployError}
            </span>
          )}
        </div>
      </div>

      {/* Build label + telemetry summary — read live from bridge-files-stable.json */}
      <div className="bg-[#F9F7F4] border border-[#F3F0EB] rounded-xl p-4 mb-6 text-sm">
        <div className="flex items-center justify-between flex-wrap gap-2 mb-2">
          <div className="font-mono text-xs text-foreground">
            Build: <span className="font-semibold">{STABLE_BUILD_VERSION}</span>
            <span className="text-muted-foreground"> · bundle_hash </span>
            <span className="font-semibold">{STABLE_BUNDLE_HASH}</span>
            <span className="text-muted-foreground">
              {" · "}{STABLE_FILE_COUNT} runtime files
              {EXTRA_FILE_COUNT > 0 ? ` + ${EXTRA_FILE_COUNT} extra (deploy-agent)` : ""}
            </span>
            {healthStatus === "ok" && healthData?.bundle_hash && (
              healthData.bundle_hash === STABLE_BUNDLE_HASH ? (
                <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-emerald-100 text-emerald-800 px-2 py-0.5 text-[10px] font-semibold">
                  ✓ /health match ({healthData.bundle_hash})
                </span>
              ) : (
                <span className="ml-2 inline-flex items-center gap-1 rounded-full bg-red-100 text-red-800 px-2 py-0.5 text-[10px] font-semibold">
                  ✗ /health mismatch ({healthData.bundle_hash}) — do NOT run test calls
                </span>
              )
            )}
          </div>
          <div className="text-xs text-muted-foreground">
            Whitelist-safe. Rollback bundle preserved in <code className="font-mono">bridge-files-stable-prev.json</code>.
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-2 text-xs text-muted-foreground">
          <div>
            <div className="font-semibold text-foreground mb-1">What&apos;s logged</div>
            <ul className="list-disc pl-4 space-y-0.5">
              <li>Per-turn: <code>user_turn_start/end</code>, <code>model_first_audio</code> (think-time), <code>model_turn_complete</code></li>
              <li>State-aware <code>turn_gap_alert</code> (think-time &gt; 3s, audio stall &gt; 5s)</li>
              <li>Greeting suppression: <code>greeting_suppress_canceled</code></li>
              <li>Silence watchdog: <code>silence_probe</code>, <code>silence_timeout_hangup</code></li>
              <li>Energy-VAD turn-end: <code>user_turn_end</code> with <code>source=energy_silence_timeout</code></li>
              <li>Verbal rating capture mapped to <code>voice_call_logs.rating</code></li>
            </ul>
          </div>
          <div>
            <div className="font-semibold text-foreground mb-1">Voice-first behavior</div>
            <ul className="list-disc pl-4 space-y-0.5">
              <li>No screen/click language; PDPA consent before recording personal data</li>
              <li>Caller-ID confirmation; one question at a time; 1–3 sentence replies</li>
              <li>End-of-call: ask for 1–5 rating verbally</li>
              <li>KB context capped (~12k chars); maxOutputTokens 300</li>
            </ul>
          </div>
        </div>
      </div>

      {/* File Tabs */}
      <Tabs defaultValue="server.ts">
        <TabsList className="bg-[#F9F7F4] border border-[#F3F0EB] mb-4 flex-wrap h-auto gap-1 p-1">
          {Object.keys(STABLE_DEPLOY_FILES).map((name) => (
            <TabsTrigger key={name} value={name} className="text-xs font-mono data-[state=active]:bg-white">
              {name}
            </TabsTrigger>
          ))}
          <TabsTrigger value="env" className="text-xs font-mono data-[state=active]:bg-white">
            .env Template
          </TabsTrigger>
          <TabsTrigger value="guide" className="text-xs font-mono data-[state=active]:bg-white">
            Deploy Guide
          </TabsTrigger>
        </TabsList>

        {Object.entries(STABLE_DEPLOY_FILES).map(([name, code]) => (
          <TabsContent key={name} value={name}>
            <CodeBlock code={code as string} filename={name} />
          </TabsContent>
        ))}

        <TabsContent value="env">
          <CodeBlock code={ENV_TEMPLATE} filename=".env" />
        </TabsContent>

        <TabsContent value="guide">
          <CodeBlock code={DEPLOY_GUIDE} filename="deploy-guide.md" />
        </TabsContent>
      </Tabs>
    </div>
  );
}
