-- Insert Global 151 carriers into database
-- Using the best network type per country based on available carrier data
INSERT INTO public.country_carriers (country_name, country_code, carrier_name, network_type, region_preset, source)
VALUES
  ('Albania', 'AL', 'Vodafone / One', '4G', 'global_151', 'manual'),
  ('Algeria', 'DZ', 'Mobilis / Orascom Telecom', '4G', 'global_151', 'manual'),
  ('Anguilla', 'AI', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('Antigua and Barbuda', 'AG', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('Argentina', 'AR', 'Claro / Telefonica', '4G', 'global_151', 'manual'),
  ('Armenia', 'AM', 'ArmenTel / VIVA', '4G', 'global_151', 'manual'),
  ('Aruba', 'AW', 'Digicel', '4G', 'global_151', 'manual'),
  ('Australia', 'AU', 'Optus / Telstra', '5G', 'global_151', 'manual'),
  ('Austria', 'AT', 'T-mobile / Orange / A1', '5G', 'global_151', 'manual'),
  ('Azerbaijan', 'AZ', 'Azercell / Bakcell', '5G', 'global_151', 'manual'),
  ('Bangladesh', 'BD', 'GrameenPhone', '4G', 'global_151', 'manual'),
  ('Barbados', 'BB', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('Belarus', 'BY', 'FE VELCOM / life', '4G', 'global_151', 'manual'),
  ('Belgium', 'BE', 'Proximus / Orange / Base', '5G', 'global_151', 'manual'),
  ('Bermuda', 'BM', 'Digicel', '4G', 'global_151', 'manual'),
  ('Bosnia and Herzegovina', 'BA', 'HT Eronet / BH Telecom', '4G', 'global_151', 'manual'),
  ('Brazil', 'BR', 'VIVO / TIM / Claro', '4G', 'global_151', 'manual'),
  ('British Virgin Islands', 'VG', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('Brunei', 'BN', 'UNN', '5G', 'global_151', 'manual'),
  ('Bulgaria', 'BG', 'Yettel / A1 / Vivacom', '5G', 'global_151', 'manual'),
  ('Cambodia', 'KH', 'CamGSM / Smart / Metfone', '4G', 'global_151', 'manual'),
  ('Cameroon', 'CM', 'Orange', '4G', 'global_151', 'manual'),
  ('Canada', 'CA', 'Bell / Telus / Rogers', '5G', 'global_151', 'manual'),
  ('Cayman Islands', 'KY', 'Digicel', '4G', 'global_151', 'manual'),
  ('Centrafrique', 'CF', 'Orange', '4G', 'global_151', 'manual'),
  ('Chile', 'CL', 'Claro / Telefonica / Entel', '4G', 'global_151', 'manual'),
  ('China', 'CN', 'CMCC', '5G', 'global_151', 'manual'),
  ('Colombia', 'CO', 'Movistar / Claro / Tigo', '4G', 'global_151', 'manual'),
  ('Costa Rica', 'CR', 'Movistar / Claro', '4G', 'global_151', 'manual'),
  ('Croatia', 'HR', 'T-mobile / A1 Hrvatska', '5G', 'global_151', 'manual'),
  ('Curacao', 'CW', 'Digicel / UTS', '4G', 'global_151', 'manual'),
  ('Cyprus', 'CY', 'CYTA / MTN Cyprus', '5G', 'global_151', 'manual'),
  ('Czech Republic', 'CZ', 'Vodafone / T-mobile / O2', '5G', 'global_151', 'manual'),
  ('Democratic Republic of Congo', 'CD', 'Airtel / Vodacom / Orange', '4G', 'global_151', 'manual'),
  ('Denmark', 'DK', 'TDC / Telia / Telenor', '5G', 'global_151', 'manual'),
  ('Dominica', 'DM', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('Dominican Republic', 'DO', 'Claro / Altice', '4G', 'global_151', 'manual'),
  ('Ecuador', 'EC', 'Claro / Telefonica', '4G', 'global_151', 'manual'),
  ('Egypt', 'EG', 'Vodafone / Orange / Etisalat', '5G', 'global_151', 'manual'),
  ('El Salvador', 'SV', 'Claro', '4G', 'global_151', 'manual'),
  ('Estonia', 'EE', 'Tele2 / Elisa / Telia', '5G', 'global_151', 'manual'),
  ('Faroe Islands', 'FO', 'Faroese Telecom', '5G', 'global_151', 'manual'),
  ('Fiji', 'FJ', 'Digicel / Vodafone', '4G', 'global_151', 'manual'),
  ('Finland', 'FI', 'Elisa / DNA / Telia', '5G', 'global_151', 'manual'),
  ('France', 'FR', 'SFR / Orange / Bouygues', '5G', 'global_151', 'manual'),
  ('French Guiana', 'GF', 'Digicel / Orange', '4G', 'global_151', 'manual'),
  ('Georgia', 'GE', 'Geocell / Mobitel', '5G', 'global_151', 'manual'),
  ('Germany', 'DE', 'Vodafone / O2 / T-mobile', '5G', 'global_151', 'manual'),
  ('Ghana', 'GH', 'MTN / Vodafone', '4G', 'global_151', 'manual'),
  ('Gibraltar', 'GI', 'Gibtel', '4G', 'global_151', 'manual'),
  ('Greece', 'GR', 'Vodafone / Cosmote / Wind', '5G', 'global_151', 'manual'),
  ('Grenada', 'GD', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('Guadeloupe', 'GP', 'Digicel / Orange', 'LTE', 'global_151', 'manual'),
  ('Guam', 'GU', 'Docomo Pacific', '4G', 'global_151', 'manual'),
  ('Guatemala', 'GT', 'Claro / Telefonica / Tigo', '4G', 'global_151', 'manual'),
  ('Guyana', 'GY', 'Digicel / GTT', '4G', 'global_151', 'manual'),
  ('Haiti', 'HT', 'Digicel', '4G', 'global_151', 'manual'),
  ('Honduras', 'HN', 'Claro / Telefonica', '4G', 'global_151', 'manual'),
  ('Hong Kong', 'HK', 'CMHK', '5G', 'global_151', 'manual'),
  ('Hungary', 'HU', 'Telenor / Vodafone / T-mobile', '5G', 'global_151', 'manual'),
  ('Iceland', 'IS', 'Siminn / Vodafone / Nova', '5G', 'global_151', 'manual'),
  ('India', 'IN', 'Reliance Jio/Bharti Airtel', '4G', 'global_151', 'manual'),
  ('Indonesia', 'ID', 'XL / Telkomsel / Indosat', '5G', 'global_151', 'manual'),
  ('Iran', 'IR', 'MTN Irancell', '4G', 'global_151', 'manual'),
  ('Ireland', 'IE', 'Meteor / 3 Ireland', '5G', 'global_151', 'manual'),
  ('Israel', 'IL', 'Partner / Cellcom / Pelephone', '5G', 'global_151', 'manual'),
  ('Italy', 'IT', 'Vodafone / TIM / WIND / Iliad', '5G', 'global_151', 'manual'),
  ('Ivory Coast', 'CI', 'MTN / Orange', '4G', 'global_151', 'manual'),
  ('Jamaica', 'JM', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('Japan', 'JP', 'KDDI / Softbank / Docomo', '5G', 'global_151', 'manual'),
  ('Jordan', 'JO', 'Zain / Umniah', '4G', 'global_151', 'manual'),
  ('Kazakhstan', 'KZ', 'Tele2 / KCell', '5G', 'global_151', 'manual'),
  ('Kenya', 'KE', 'Airtel', '4G', 'global_151', 'manual'),
  ('Kuwait', 'KW', 'Ooredoo', '5G', 'global_151', 'manual'),
  ('Kyrgyzstan', 'KG', 'Beeline / Alfa Telecom', '4G', 'global_151', 'manual'),
  ('Laos', 'LA', 'LTC', '5G', 'global_151', 'manual'),
  ('Latvia', 'LV', 'Tele2 / BITE / LMT', '5G', 'global_151', 'manual'),
  ('Liberia', 'LR', 'Cellcom / Orange', '4G', 'global_151', 'manual'),
  ('Lithuania', 'LT', 'BITE / Tele2 / Omnitel', '5G', 'global_151', 'manual'),
  ('Luxembourg', 'LU', 'TANGO / POST / Orange', '5G', 'global_151', 'manual'),
  ('Macau', 'MO', 'CTM', '5G', 'global_151', 'manual'),
  ('Madagascar', 'MG', 'Airtel / Orange', '4G', 'global_151', 'manual'),
  ('Malaysia', 'MY', 'Maxis / Celcom / Digi', '5G', 'global_151', 'manual'),
  ('Malta', 'MT', 'Vodafone / GO', '5G', 'global_151', 'manual'),
  ('Malawi', 'MW', 'Airtel', '4G', 'global_151', 'manual'),
  ('Martinique', 'MQ', 'Digicel / Orange', '4G', 'global_151', 'manual'),
  ('Mauritius', 'MU', 'Emtel / Orange', '4G', 'global_151', 'manual'),
  ('Mexico', 'MX', 'Movistar / Telcel / AT&T', '5G', 'global_151', 'manual'),
  ('Moldova', 'MD', 'Orange', '4G', 'global_151', 'manual'),
  ('Mongolia', 'MN', 'Unitel / Mobicom', '4G', 'global_151', 'manual'),
  ('Montenegro', 'ME', 'Telenor / T-mobile / Mtel', '4G', 'global_151', 'manual'),
  ('Morocco', 'MA', 'Orange / Maroc Telecom', '4G', 'global_151', 'manual'),
  ('Mozambique', 'MZ', 'Vodacom / Mcel / Movitel', '4G', 'global_151', 'manual'),
  ('Nepal', 'NP', 'Nepal Telecom', '4G', 'global_151', 'manual'),
  ('Netherlands', 'NL', 'Vodafone / KPN / T-mobile', '5G', 'global_151', 'manual'),
  ('New Zealand', 'NZ', 'Spark / Vodafone / 2 Degrees', '5G', 'global_151', 'manual'),
  ('Nicaragua', 'NI', 'Claro', '4G', 'global_151', 'manual'),
  ('Norway', 'NO', 'Telia / Telenor', '5G', 'global_151', 'manual'),
  ('Oman', 'OM', 'Omantel / Ooredoo', '5G', 'global_151', 'manual'),
  ('Pakistan', 'PK', 'CMPak', '4G', 'global_151', 'manual'),
  ('Panama', 'PA', 'Tigo / C&W / Claro', '4G', 'global_151', 'manual'),
  ('Papua New Guinea', 'PG', 'Digicel', '4G', 'global_151', 'manual'),
  ('Paraguay', 'PY', 'Claro', '4G', 'global_151', 'manual'),
  ('Peru', 'PE', 'Claro / Telefonica', '4G', 'global_151', 'manual'),
  ('Philippines', 'PH', 'Smart / Globe', '5G', 'global_151', 'manual'),
  ('Poland', 'PL', 'Orange / T-mobile / Plus / P4', '5G', 'global_151', 'manual'),
  ('Portugal', 'PT', 'MEO / NOS / Vodafone', '5G', 'global_151', 'manual'),
  ('Qatar', 'QA', 'Ooredoo / Vodafone', '5G', 'global_151', 'manual'),
  ('Romania', 'RO', 'Vodafone / Orange / Digi', '5G', 'global_151', 'manual'),
  ('Russia', 'RU', 'MTS', '4G', 'global_151', 'manual'),
  ('Russia', 'RU', 'Tele2/Beeline', '4G', 'global_151', 'manual'),
  ('Rwanda', 'RW', 'MTN / Tigo / Airtel', '4G', 'global_151', 'manual'),
  ('Saudi Arabia', 'SA', 'Mobily', '5G', 'global_151', 'manual'),
  ('Serbia', 'RS', 'Telenor / Telekom / A1', '4G', 'global_151', 'manual'),
  ('Seychelles', 'SC', 'Airtel / C&W', '4G', 'global_151', 'manual'),
  ('Sierra Leone', 'SL', 'Orange / Africell', '4G', 'global_151', 'manual'),
  ('Singapore', 'SG', 'Singtel', '5G', 'global_151', 'manual'),
  ('Slovakia', 'SK', 'O2 / Orange', '4G', 'global_151', 'manual'),
  ('Slovenia', 'SI', 'A1 / Telekom', '5G', 'global_151', 'manual'),
  ('South Africa', 'ZA', 'Vodacom / MTN / Telkom', '4G', 'global_151', 'manual'),
  ('South Korea', 'KR', 'LGU / SK / KT', '5G', 'global_151', 'manual'),
  ('Spain', 'ES', 'Orange / Telefonica / Vodafone', '5G', 'global_151', 'manual'),
  ('Sri Lanka', 'LK', 'Dialog', '4G', 'global_151', 'manual'),
  ('St. Kitts/Nevis', 'KN', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('St. Lucia', 'LC', 'Digicel', '4G', 'global_151', 'manual'),
  ('St. Vincent', 'VC', 'Digicel', '4G', 'global_151', 'manual'),
  ('Sudan', 'SD', 'MTN / Zain', '4G', 'global_151', 'manual'),
  ('Swaziland', 'SZ', 'MTN', '4G', 'global_151', 'manual'),
  ('Sweden', 'SE', 'Telenor / Telia / Tele2', '5G', 'global_151', 'manual'),
  ('Switzerland', 'CH', 'Sunrise / SALT / Swisscom', '5G', 'global_151', 'manual'),
  ('Taiwan', 'TW', 'Chunghwa', '5G', 'global_151', 'manual'),
  ('Tajikistan', 'TJ', 'Beeline / Tcell', '4G', 'global_151', 'manual'),
  ('Tanzania', 'TZ', 'Vodacom / Airtel', '4G', 'global_151', 'manual'),
  ('Thailand', 'TH', 'Truemove / DTAC', '5G', 'global_151', 'manual'),
  ('Tonga', 'TO', 'Digicel', '4G', 'global_151', 'manual'),
  ('Trinidad and Tobago', 'TT', 'Digicel', '4G', 'global_151', 'manual'),
  ('Tunisia', 'TN', 'Tunisie Telecom / Ooredoo / Orange', '4G', 'global_151', 'manual'),
  ('Turkey', 'TR', 'Turkcell / Vodafone / AVEA', '5G', 'global_151', 'manual'),
  ('Turks and Caicos', 'TC', 'Digicel / C&W', '4G', 'global_151', 'manual'),
  ('UAE', 'AE', 'Etisalat / DU', '5G', 'global_151', 'manual'),
  ('Uganda', 'UG', 'Airtel / MTN', '4G', 'global_151', 'manual'),
  ('Ukraine', 'UA', 'Vodafone / Kyivstar / Lifecell', '4G', 'global_151', 'manual'),
  ('United Kingdom', 'GB', 'Vodafone / EE / O2 / 3UK', '5G', 'global_151', 'manual'),
  ('Uruguay', 'UY', 'Antel / Telefonica / Claro', '5G', 'global_151', 'manual'),
  ('USA', 'US', 'AT&T / T-Mobile', '5G', 'global_151', 'manual'),
  ('Uzbekistan', 'UZ', 'Unitel', '5G', 'global_151', 'manual'),
  ('Vanuatu', 'VU', 'Digicel', '4G', 'global_151', 'manual'),
  ('Vatican City', 'VA', 'Vodafone / TIM / WIND', '4G', 'global_151', 'manual'),
  ('Vietnam', 'VN', 'Vinaphone / Mobifone / Viettel', '4G', 'global_151', 'manual'),
  ('Yemen', 'YE', 'MTN Yemen', '4G', 'global_151', 'manual'),
  ('Zambia', 'ZM', 'Airtel', '4G', 'global_151', 'manual'),
  ('San Marino', 'SM', 'Vodafone / TIM / WIND', '4G', 'global_151', 'manual')
ON CONFLICT DO NOTHING;