
-- Step 1: Delete all existing global_109 entries
DELETE FROM public.country_carriers WHERE region_preset = 'global_109';

-- Step 2: Insert the correct 115 countries with USIMSA carrier names and DB-derived network types
INSERT INTO public.country_carriers (country_name, country_code, carrier_name, network_type, region_preset, source) VALUES
('Greece', 'GR', 'Vodafone / Cosmote / Wind Hellas', '5G', 'global_109', 'usimsa_spec'),
('Netherlands', 'NL', 'Vodafone / KPN', '5G', 'global_109', 'usimsa_spec'),
('Belgium', 'BE', 'Proximus / Orange', '5G', 'global_109', 'usimsa_spec'),
('France', 'FR', 'SFR / Orange', '5G', 'global_109', 'usimsa_spec'),
('Spain', 'ES', 'Orange / Telefonica / Vodafone', '5G', 'global_109', 'usimsa_spec'),
('Hungary', 'HU', 'Telenor / Vodafone', '5G', 'global_109', 'usimsa_spec'),
('Bosnia and Herzegovina', 'BA', 'HT (Eronet)', 'LTE', 'global_109', 'usimsa_spec'),
('Croatia', 'HR', 'T-mobile / A1 Hrvatska', '5G', 'global_109', 'usimsa_spec'),
('Serbia', 'RS', 'Telenor', 'LTE', 'global_109', 'usimsa_spec'),
('Italy', 'IT', 'Vodafone / TIM', '5G', 'global_109', 'usimsa_spec'),
('Romania', 'RO', 'Vodafone', 'LTE', 'global_109', 'usimsa_spec'),
('Switzerland', 'CH', 'Sunrise / SALT', '5G', 'global_109', 'usimsa_spec'),
('Czech Republic', 'CZ', 'Vodafone / T-mobile', '5G', 'global_109', 'usimsa_spec'),
('Slovakia', 'SK', 'O2 / Orange', '5G', 'global_109', 'usimsa_spec'),
('Austria', 'AT', 'T-mobile / Orange (H3G)', '5G', 'global_109', 'usimsa_spec'),
('United Kingdom', 'GB', 'Vodafone / EE / O2', '5G', 'global_109', 'usimsa_spec'),
('Denmark', 'DK', 'TDC / Telia', '5G', 'global_109', 'usimsa_spec'),
('Sweden', 'SE', 'Telenor / TeliaSonera', '5G', 'global_109', 'usimsa_spec'),
('Norway', 'NO', 'Telia / Telenor', '5G', 'global_109', 'usimsa_spec'),
('Finland', 'FI', 'Elisa', '5G', 'global_109', 'usimsa_spec'),
('Lithuania', 'LT', 'BITE / Tele2', '5G', 'global_109', 'usimsa_spec'),
('Latvia', 'LV', 'Tele2', '5G', 'global_109', 'usimsa_spec'),
('Estonia', 'EE', 'Tele2 / Elisa EMT', '5G', 'global_109', 'usimsa_spec'),
('Ukraine', 'UA', 'Vodafone / Kyivstar', 'LTE', 'global_109', 'usimsa_spec'),
('Moldova', 'MD', 'Orange', '4G', 'global_109', 'usimsa_spec'),
('Poland', 'PL', 'Orange / T-mobile', '5G', 'global_109', 'usimsa_spec'),
('Germany', 'DE', 'Vodafone / O2', '5G', 'global_109', 'usimsa_spec'),
('Gibraltar', 'GI', 'Gibtel', '4G', 'global_109', 'usimsa_spec'),
('Portugal', 'PT', 'TMN / NOS / Vodafone', '5G', 'global_109', 'usimsa_spec'),
('Luxembourg', 'LU', 'TANGO / POST / Orange', '5G', 'global_109', 'usimsa_spec'),
('Ireland', 'IE', 'Meteor', '5G', 'global_109', 'usimsa_spec'),
('Iceland', 'IS', 'Siminn', '5G', 'global_109', 'usimsa_spec'),
('Albania', 'AL', 'Vodafone', 'LTE', 'global_109', 'usimsa_spec'),
('Malta', 'MT', 'Epic / GO', '5G', 'global_109', 'usimsa_spec'),
('Cyprus', 'CY', 'CYTA', 'LTE', 'global_109', 'usimsa_spec'),
('Georgia', 'GE', 'Geocell / Mobitel', '4G', 'global_109', 'usimsa_spec'),
('Armenia', 'AM', 'ArmenTel', '4G', 'global_109', 'usimsa_spec'),
('Bulgaria', 'BG', 'Yettel (Telenor)', '5G', 'global_109', 'usimsa_spec'),
('Turkey', 'TR', 'Turkcell', '5G', 'global_109', 'usimsa_spec'),
('Slovenia', 'SI', 'A1 (Si Mobile)', '5G', 'global_109', 'usimsa_spec'),
('Faroe Islands', 'FO', 'Faroese Telecom', '5G', 'global_109', 'usimsa_spec'),
('French Guiana', 'GF', 'Digicel', '4G', 'global_109', 'usimsa_spec'),
('Martinique', 'MQ', 'Digicel', '4G', 'global_109', 'usimsa_spec'),
('Montenegro', 'ME', 'Telenor', '4G', 'global_109', 'usimsa_spec'),
('Russia', 'RU', 'MTS / T2 Mobile', '4G', 'global_109', 'usimsa_spec'),
('Qatar', 'QA', 'Ooredoo / Vodafone', '5G', 'global_109', 'usimsa_spec'),
('United Arab Emirates', 'AE', 'Etisalat / DU', '5G', 'global_109', 'usimsa_spec'),
('Canada', 'CA', 'Bell / Telus / Sasktel', '5G', 'global_109', 'usimsa_spec'),
('United States', 'US', 'AT&T / T-Mobile', '5G', 'global_109', 'usimsa_spec'),
('Mexico', 'MX', 'Telefonica / Telcel', '5G', 'global_109', 'usimsa_spec'),
('Dominican Republic', 'DO', 'Claro / Altice', '4G', 'global_109', 'usimsa_spec'),
('Azerbaijan', 'AZ', 'Azercell', '5G', 'global_109', 'usimsa_spec'),
('Kazakhstan', 'KZ', 'Tele2', '5G', 'global_109', 'usimsa_spec'),
('India', 'IN', 'Airtel', '4G', 'global_109', 'usimsa_spec'),
('Pakistan', 'PK', 'CMPak', '4G', 'global_109', 'usimsa_spec'),
('Sri Lanka', 'LK', 'Dialog', '4G', 'global_109', 'usimsa_spec'),
('Jordan', 'JO', 'Zain', '4G', 'global_109', 'usimsa_spec'),
('Kuwait', 'KW', 'Ooredoo', '5G', 'global_109', 'usimsa_spec'),
('Saudi Arabia', 'SA', 'Mobily', '5G', 'global_109', 'usimsa_spec'),
('Yemen', 'YE', 'MTN', '4G', 'global_109', 'usimsa_spec'),
('Oman', 'OM', 'Omantel', '5G', 'global_109', 'usimsa_spec'),
('Israel', 'IL', 'Partner / Cellcom', '5G', 'global_109', 'usimsa_spec'),
('Mongolia', 'MN', 'Unitel', '4G', 'global_109', 'usimsa_spec'),
('Nepal', 'NP', 'Nepal Telecom', '4G', 'global_109', 'usimsa_spec'),
('Iran', 'IR', 'MTN Irancell', '4G', 'global_109', 'usimsa_spec'),
('Uzbekistan', 'UZ', 'Unitel', '4G', 'global_109', 'usimsa_spec'),
('Tajikistan', 'TJ', 'Beeline', '4G', 'global_109', 'usimsa_spec'),
('Japan', 'JP', 'KDDI / Softbank', '5G', 'global_109', 'usimsa_spec'),
('Vietnam', 'VN', 'Viettel / Vinaphone / Mobifone', '5G', 'global_109', 'usimsa_spec'),
('Hong Kong', 'HK', 'CMHK', '4G', 'global_109', 'usimsa_spec'),
('Macau', 'MO', 'CTM', '5G', 'global_109', 'usimsa_spec'),
('Cambodia', 'KH', 'CamGSM', '4G', 'global_109', 'usimsa_spec'),
('China', 'CN', 'CMCC', '5G', 'global_109', 'usimsa_spec'),
('Bangladesh', 'BD', 'GrameenPhone', '4G', 'global_109', 'usimsa_spec'),
('Taiwan', 'TW', 'Chunghwa', '4G', 'global_109', 'usimsa_spec'),
('Malaysia', 'MY', 'Maxis / Celcom', '4G', 'global_109', 'usimsa_spec'),
('Australia', 'AU', 'Optus', '5G', 'global_109', 'usimsa_spec'),
('Indonesia', 'ID', 'XL / Indosat / Telkomsel', '4G', 'global_109', 'usimsa_spec'),
('Philippines', 'PH', 'Smart', '5G', 'global_109', 'usimsa_spec'),
('Thailand', 'TH', 'Truemove', '5G', 'global_109', 'usimsa_spec'),
('Singapore', 'SG', 'Singtel', '5G', 'global_109', 'usimsa_spec'),
('Brunei', 'BN', 'UNN', '5G', 'global_109', 'usimsa_spec'),
('New Zealand', 'NZ', 'Spark / Vodafone', '5G', 'global_109', 'usimsa_spec'),
('Papua New Guinea', 'PG', 'Digicel', '4G', 'global_109', 'usimsa_spec'),
('Tonga', 'TO', 'Digicel', '4G', 'global_109', 'usimsa_spec'),
('Vanuatu', 'VU', 'Digicel', '4G', 'global_109', 'usimsa_spec'),
('Fiji', 'FJ', 'Digicel', '4G', 'global_109', 'usimsa_spec'),
('Egypt', 'EG', 'Vodafone / Etisalat', '5G', 'global_109', 'usimsa_spec'),
('Algeria', 'DZ', 'Mobilis', '4G', 'global_109', 'usimsa_spec'),
('Morocco', 'MA', 'Orange Morocco', '4G', 'global_109', 'usimsa_spec'),
('Cote d''Ivoire', 'CI', 'MTN', '4G', 'global_109', 'usimsa_spec'),
('Mauritius', 'MU', 'Emtel', '4G', 'global_109', 'usimsa_spec'),
('Liberia', 'LR', 'Cellcom Liberia', '4G', 'global_109', 'usimsa_spec'),
('Ghana', 'GH', 'MTN / Vodafone', '4G', 'global_109', 'usimsa_spec'),
('DR Congo', 'CD', 'Airtel / Vodacom', '4G', 'global_109', 'usimsa_spec'),
('Seychelles', 'SC', 'Airtel', '4G', 'global_109', 'usimsa_spec'),
('Sudan', 'SD', 'MTN', '4G', 'global_109', 'usimsa_spec'),
('Rwanda', 'RW', 'MTN Rwanda Cell', '4G', 'global_109', 'usimsa_spec'),
('Kenya', 'KE', 'Airtel', '4G', 'global_109', 'usimsa_spec'),
('Tanzania', 'TZ', 'Vodacom', '4G', 'global_109', 'usimsa_spec'),
('Uganda', 'UG', 'Airtel', '4G', 'global_109', 'usimsa_spec'),
('Mozambique', 'MZ', 'Vodacom', '4G', 'global_109', 'usimsa_spec'),
('Zambia', 'ZM', 'Airtel', '4G', 'global_109', 'usimsa_spec'),
('Madagascar', 'MG', 'Airtel', '4G', 'global_109', 'usimsa_spec'),
('Malawi', 'MW', 'Airtel', '4G', 'global_109', 'usimsa_spec'),
('South Africa', 'ZA', 'MTN / Vodacom', '5G', 'global_109', 'usimsa_spec'),
('Guatemala', 'GT', 'Claro / Telefonica', '4G', 'global_109', 'usimsa_spec'),
('Costa Rica', 'CR', 'Telefonica', '4G', 'global_109', 'usimsa_spec'),
('Panama', 'PA', 'Telefonica', '4G', 'global_109', 'usimsa_spec'),
('Peru', 'PE', 'Claro / Telefonica', '4G', 'global_109', 'usimsa_spec'),
('Argentina', 'AR', 'Claro / Telefonica', '4G', 'global_109', 'usimsa_spec'),
('Brazil', 'BR', 'VIVO', '4G', 'global_109', 'usimsa_spec'),
('Chile', 'CL', 'Claro / Telefonica', '4G', 'global_109', 'usimsa_spec'),
('Colombia', 'CO', 'Telefonica / Claro', '4G', 'global_109', 'usimsa_spec'),
('Uruguay', 'UY', 'Antel / Telefonica', '4G', 'global_109', 'usimsa_spec');
