
INSERT INTO country_carriers (country_name, country_code, carrier_name, network_type, region_preset, source) VALUES
('Austria', 'AT', 'H3G', '5G', 'europe_33', 'tuge_eo1'),
('Austria', 'AT', 'T-Mobile', '5G', 'europe_33', 'tuge_eo1'),
('Austria', 'AT', 'A1', '5G', 'europe_33', 'tuge_eo1'),
('Belgium', 'BE', 'Telenet', '4G', 'europe_33', 'tuge_eo1'),
('Belgium', 'BE', 'ORANGE', '5G', 'europe_33', 'tuge_eo1'),
('Bulgaria', 'BG', 'Mobiltel', '5G', 'europe_33', 'tuge_eo1'),
('Bulgaria', 'BG', 'Telenor', 'LTE', 'europe_33', 'tuge_eo1'),
('Bulgaria', 'BG', 'Vivacom', '5G', 'europe_33', 'tuge_eo1'),
('Switzerland', 'CH', 'Swisscom', '5G', 'europe_33', 'tuge_eo1'),
('Switzerland', 'CH', 'Sunrise', '5G', 'europe_33', 'tuge_eo1'),
('Switzerland', 'CH', 'Salt', '5G', 'europe_33', 'tuge_eo1'),
('Cyprus', 'CY', 'CYTA', 'LTE', 'europe_33', 'tuge_eo1'),
('Cyprus', 'CY', 'Primetel', '3G', 'europe_33', 'tuge_eo1'),
('Cyprus', 'CY', 'Epic', '4G', 'europe_33', 'tuge_eo1'),
('Czech Republic', 'CZ', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Czech Republic', 'CZ', 'O2', '5G', 'europe_33', 'tuge_eo1'),
('Czech Republic', 'CZ', 'T-Mobile', '5G', 'europe_33', 'tuge_eo1'),
('Germany', 'DE', 'T-Mobile', '5G', 'europe_33', 'tuge_eo1'),
('Germany', 'DE', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Denmark', 'DK', 'Telenor', 'LTE', 'europe_33', 'tuge_eo1'),
('Denmark', 'DK', 'HI3G', 'LTE', 'europe_33', 'tuge_eo1'),
('Denmark', 'DK', 'Telia', '5G', 'europe_33', 'tuge_eo1'),
('Denmark', 'DK', 'TDC', '5G', 'europe_33', 'tuge_eo1'),
('Denmark', 'DK', 'nuuday', '4G', 'europe_33', 'tuge_eo1'),
('Spain', 'ES', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Spain', 'ES', 'Orange', '5G', 'europe_33', 'tuge_eo1'),
('Spain', 'ES', 'Yoigo', 'LTE', 'europe_33', 'tuge_eo1'),
('Estonia', 'EE', 'Telia', '5G', 'europe_33', 'tuge_eo1'),
('Estonia', 'EE', 'Tele2', '5G', 'europe_33', 'tuge_eo1'),
('Estonia', 'EE', 'Elisa', '5G', 'europe_33', 'tuge_eo1'),
('Finland', 'FI', 'DNA', '5G', 'europe_33', 'tuge_eo1'),
('Finland', 'FI', 'Elisa', '5G', 'europe_33', 'tuge_eo1'),
('Finland', 'FI', 'Telia', '5G', 'europe_33', 'tuge_eo1'),
('France', 'FR', 'Orange', '5G', 'europe_33', 'tuge_eo1'),
('France', 'FR', 'Bouygues', '5G', 'europe_33', 'tuge_eo1'),
('France', 'FR', 'Free Mobile', '5G', 'europe_33', 'tuge_eo1'),
('United Kingdom', 'GB', 'H3G', '5G', 'europe_33', 'tuge_eo1'),
('United Kingdom', 'GB', 'EE', '5G', 'europe_33', 'tuge_eo1'),
('United Kingdom', 'GB', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Greece', 'GR', 'Cosmote', '5G', 'europe_33', 'tuge_eo1'),
('Greece', 'GR', 'Vodafone', '5G', 'europe_33', 'tuge_eo1'),
('Greece', 'GR', 'Wind(Nova)', '5G', 'europe_33', 'tuge_eo1'),
('Croatia', 'HR', 'Hrvatski', '5G', 'europe_33', 'tuge_eo1'),
('Croatia', 'HR', 'Tele2', 'LTE', 'europe_33', 'tuge_eo1'),
('Croatia', 'HR', 'VIPnet', 'LTE', 'europe_33', 'tuge_eo1'),
('Hungary', 'HU', 'Telenor', '5G', 'europe_33', 'tuge_eo1'),
('Hungary', 'HU', 'T-Mobile', '5G', 'europe_33', 'tuge_eo1'),
('Hungary', 'HU', 'Vodafone', '5G', 'europe_33', 'tuge_eo1'),
('Ireland', 'IE', 'H3G', '5G', 'europe_33', 'tuge_eo1'),
('Ireland', 'IE', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Iceland', 'IS', 'Landssiminn - ISLPS', '5G', 'europe_33', 'tuge_eo1'),
('Italy', 'IT', 'ILIAD', '5G', 'europe_33', 'tuge_eo1'),
('Italy', 'IT', 'H3G', '5G', 'europe_33', 'tuge_eo1'),
('Italy', 'IT', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Italy', 'IT', 'Telecom', '5G', 'europe_33', 'tuge_eo1'),
('Italy', 'IT', 'Wind', '5G', 'europe_33', 'tuge_eo1'),
('Liechtenstein', 'LI', 'Orange', '4G', 'europe_33', 'tuge_eo1'),
('Liechtenstein', 'LI', 'Telecom AG', 'LTE', 'europe_33', 'tuge_eo1'),
('Lithuania', 'LT', 'Tele2', '5G', 'europe_33', 'tuge_eo1'),
('Lithuania', 'LT', 'Bite', '5G', 'europe_33', 'tuge_eo1'),
('Lithuania', 'LT', 'Omnitel', '5G', 'europe_33', 'tuge_eo1'),
('Luxembourg', 'LU', 'Orange', '5G', 'europe_33', 'tuge_eo1'),
('Latvia', 'LV', 'Tele2', '5G', 'europe_33', 'tuge_eo1'),
('Latvia', 'LV', 'Bite', 'LTE', 'europe_33', 'tuge_eo1'),
('Latvia', 'LV', 'Mobilais', '4G', 'europe_33', 'tuge_eo1'),
('Moldova', 'MD', 'Orange', '4G', 'europe_33', 'tuge_eo1'),
('Malta', 'MT', 'GO', 'LTE', 'europe_33', 'tuge_eo1'),
('Malta', 'MT', 'Vodafone', '5G', 'europe_33', 'tuge_eo1'),
('Netherlands', 'NL', 'Vodafone', '5G', 'europe_33', 'tuge_eo1'),
('Netherlands', 'NL', 'Odido', '5G', 'europe_33', 'tuge_eo1'),
('Netherlands', 'NL', 'KPN', '5G', 'europe_33', 'tuge_eo1'),
('Netherlands', 'NL', 'Telfort', '4G', 'europe_33', 'tuge_eo1'),
('Norway', 'NO', 'Telia', '5G', 'europe_33', 'tuge_eo1'),
('Norway', 'NO', 'Network AS', '4G', 'europe_33', 'tuge_eo1'),
('Norway', 'NO', 'Telenor', '5G', 'europe_33', 'tuge_eo1'),
('Portugal', 'PT', 'Optimus', 'LTE', 'europe_33', 'tuge_eo1'),
('Portugal', 'PT', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Romania', 'RO', 'DIGI', '4G', 'europe_33', 'tuge_eo1'),
('Romania', 'RO', 'Telekom', 'LTE', 'europe_33', 'tuge_eo1'),
('Romania', 'RO', 'Vodafone', 'LTE', 'europe_33', 'tuge_eo1'),
('Romania', 'RO', 'Orange', '5G', 'europe_33', 'tuge_eo1'),
('Slovakia', 'SK', 'Slovak Telekom (DT)', '5G', 'europe_33', 'tuge_eo1'),
('Slovakia', 'SK', 'Orange', '5G', 'europe_33', 'tuge_eo1'),
('Slovakia', 'SK', 'O2', 'LTE', 'europe_33', 'tuge_eo1'),
('Slovenia', 'SI', 'Telekom', '5G', 'europe_33', 'tuge_eo1'),
('Slovenia', 'SI', 'A1', 'LTE', 'europe_33', 'tuge_eo1'),
('Slovenia', 'SI', 'Telemach', '5G', 'europe_33', 'tuge_eo1'),
('Sweden', 'SE', 'Telenor (Vodafone)', '5G', 'europe_33', 'tuge_eo1'),
('Sweden', 'SE', 'H3G', '5G', 'europe_33', 'tuge_eo1'),
('Sweden', 'SE', 'Tele2', '5G', 'europe_33', 'tuge_eo1'),
('Sweden', 'SE', 'Telia', '5G', 'europe_33', 'tuge_eo1'),
('Ukraine', 'UA', 'lifecell', 'LTE', 'europe_33', 'tuge_eo1'),
('Ukraine', 'UA', 'KyivStar', 'LTE', 'europe_33', 'tuge_eo1'),
('Ukraine', 'UA', 'Beeline', 'LTE', 'europe_33', 'tuge_eo1'),
('Ukraine', 'UA', 'KyivStar-RS', 'LTE', 'europe_33', 'tuge_eo1'),
('Ukraine', 'UA', 'MTS', 'LTE', 'europe_33', 'tuge_eo1');
