
INSERT INTO public.country_carriers (country_name, country_code, carrier_name, network_type, region_preset) VALUES
-- French Polynesia to Guatemala
('French Polynesia', 'PF', 'Tikiphone S.A. (Vini)', '4G', 'global_109'),
('Gambia', 'GM', 'Africell (Gambia) Ltd.', '4G', 'global_109'),
('Georgia', 'GE', 'Geocell Ltd', '5G', 'global_109'),
('Germany', 'DE', 'Vodafone D2 GmbH', '5G', 'global_109'),
('Germany', 'DE', 'O2', '5G', 'global_109'),
('Ghana', 'GH', 'ScanCom Ltd. (MTN)', '4G', 'global_109'),
('Gibraltar', 'GI', 'Gibtelecom Ltd.', '4G', 'global_109'),
('Greece', 'GR', 'WIND Hellas Telecommunications S.A.', '5G', 'global_109'),
('Guadeloupe', 'GP', 'Digicel', 'LTE', 'global_109'),
('Guatemala', 'GT', 'Tigo', '4G', 'global_109'),
-- Guernsey to India
('Guernsey', 'GG', 'Sure', '4G', 'global_109'),
('Guernsey', 'GG', 'JT (Jersey) Ltd', '4G', 'global_109'),
('Guyana', 'GY', 'Digicel Guyana', '4G', 'global_109'),
('Honduras', 'HN', 'Telefonica Celular S.A. (Celtel / Tigo)', '4G', 'global_109'),
('Hong Kong', 'HK', 'CSL', '5G', 'global_109'),
('Hungary', 'HU', 'Telenor Hungary Ltd. (former: Pannon GSM Telekommunication)', '4G', 'global_109'),
('Hungary', 'HU', 'Vodafone Hungary Ltd.', '5G', 'global_109'),
('Iceland', 'IS', 'Siminn / Iceland Telecom Ltd.', '5G', 'global_109'),
('India', 'IN', 'Reliance Jio West Bengal', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Andhra Pradesh', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Assam', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Bihar', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Gujarat', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Haryana', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Himachal Pradesh', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Karnataka', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Kerala', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Madhya Pradesh', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Maharashtra', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India North East', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Orissa', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Punjab', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Rajasthan', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Tamil Nadu', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Uttar Pradesh (West)', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Uttar Pradesh (East)', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Delhi', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio India Kolkata', '4G', 'global_109'),
('India', 'IN', 'Reliance Jio Infocomm Limited', '4G', 'global_109'),
-- Indonesia to Italy
('Indonesia', 'ID', 'PT Telekomunikasi Selular (Telkomsel)', '5G', 'global_109'),
('Ireland', 'IE', 'Meteor Mobile Telecommunications Ltd.', '5G', 'global_109'),
('Israel', 'IL', 'Cellcom Israel Ltd.', '5G', 'global_109'),
('Israel', 'IL', 'Pelephone Communications Ltd', '5G', 'global_109'),
('Italy', 'IT', 'ILIAD Italia S.p.A.', '5G', 'global_109'),
('Italy', 'IT', 'TIM Italy', '5G', 'global_109'),
('Italy', 'IT', 'Wind Tre S.p.A.', '5G', 'global_109'),
-- Jamaica to Liberia
('Jamaica', 'JM', 'Digicel Jamaica', '4G', 'global_109'),
('Japan', 'JP', 'SoftBank Corp.', '5G', 'global_109'),
('Japan', 'JP', 'KDDI', '4G', 'global_109'),
('Jersey', 'JE', 'Sure', '4G', 'global_109'),
('Jersey', 'JE', 'JT (Jersey) Ltd', '4G', 'global_109'),
('Jordan', 'JO', 'Zain JO', '4G', 'global_109'),
('Kazakhstan', 'KZ', 'Kcell', '5G', 'global_109'),
('Kenya', 'KE', 'Airtel Networks Kenya Ltd.', '4G', 'global_109'),
('Kuwait', 'KW', 'Kuwait Telecom Company', '5G', 'global_109'),
('Latvia', 'LV', 'Tele2 Latvia', '5G', 'global_109'),
('Latvia', 'LV', 'Latvian Mobile Telephone Co.', '5G', 'global_109'),
('Liberia', 'LR', 'Orange Liberia', '4G', 'global_109'),
-- Liechtenstein to Moldova
('Liechtenstein', 'LI', 'Telecom Liechtenstein AG', '5G', 'global_109'),
('Liechtenstein', 'LI', 'Salt (Liechtenstein) AG', '4G', 'global_109'),
('Lithuania', 'LT', 'Tele2 UAB Lithuania', '5G', 'global_109'),
('Lithuania', 'LT', 'Telia Lietuva, AB', '5G', 'global_109'),
('Luxembourg', 'LU', 'Tango S.A.', '5G', 'global_109'),
('Macao', 'MO', 'CTM', '5G', 'global_109'),
('Madagascar', 'MG', 'Orange Madagascar S.A.', '4G', 'global_109'),
('Malaysia', 'MY', 'Maxis', '5G', 'global_109'),
('Malaysia', 'MY', 'Celcom Axiata Berhad', '5G', 'global_109'),
('Mali', 'ML', 'Orange Mali', '4G', 'global_109'),
('Malta', 'MT', 'Vodafone Malta Limited', '5G', 'global_109'),
('Mexico', 'MX', 'Telefonica Moviles (Movistar) Mexico', '4G', 'global_109'),
('Mexico', 'MX', 'Telcel Mexico', '5G', 'global_109'),
('Moldova', 'MD', 'Orange Moldova', '4G', 'global_109'),
-- Monaco to Nigeria
('Monaco', 'MC', 'Monaco Telecom S.A.M.', '5G', 'global_109'),
('Mongolia', 'MN', 'Unitel', '4G', 'global_109'),
('Montenegro', 'ME', 'MTEL d.o.o', '4G', 'global_109'),
('Montenegro', 'ME', 'Crnogorski Telekom A.D.', '4G', 'global_109'),
('Morocco', 'MA', 'Medi Telecom S.A', '4G', 'global_109'),
('Mozambique', 'MZ', 'Movitel', '4G', 'global_109'),
('Netherlands', 'NL', 'KPN', '5G', 'global_109'),
('New Zealand', 'NZ', 'Spark New Zealand', '5G', 'global_109'),
('Nicaragua', 'NI', 'Telefonica Moviles Nicaragua', '4G', 'global_109'),
('Nigeria', 'NG', 'Airtel Networks Nigeria Ltd. (Zain/Celtel)', '4G', 'global_109'),
-- North Macedonia to Poland
('North Macedonia', 'MK', 'one.Vip DOO Skopje (MDKCC and MKDNO)', '4G', 'global_109'),
('Norway', 'NO', 'Telia Norge AS', '5G', 'global_109'),
('Norway', 'NO', 'Telenor Norge', '4G', 'global_109'),
('Oman', 'OM', 'Ooredoo (Omani Qatari Telecommunications Co. S.A.)', '5G', 'global_109'),
('Pakistan', 'PK', 'Telenor Pakistan', '4G', 'global_109'),
('Panama', 'PA', 'Telefonica Moviles Panama', '4G', 'global_109'),
('Paraguay', 'PY', 'Telefonica Celular del Paraguay S.A. (Telecel)', '4G', 'global_109'),
('Peru', 'PE', 'Claro', '4G', 'global_109'),
('Philippines', 'PH', 'Globe Telecom', '5G', 'global_109'),
('Poland', 'PL', 'ORANGE (PTK Centertel Sp. z.o.o.)', '5G', 'global_109'),
('Poland', 'PL', 'Polkomtel S.A.', '5G', 'global_109'),
-- Portugal to Serbia
('Portugal', 'PT', 'MEO', '5G', 'global_109'),
('Puerto Rico', 'PR', 'Claro', '5G', 'global_109'),
('Qatar', 'QA', 'Ooredoo', '5G', 'global_109'),
('Republic of the Congo', 'CG', 'MTN Congo', '4G', 'global_109'),
('Réunion', 'RE', 'Orange Reunion', '5G', 'global_109'),
('Romania', 'RO', 'Telekom Romania Mobile Communications', '4G', 'global_109'),
('Romania', 'RO', 'Vodafone Romania S.A.', '4G', 'global_109'),
('Romania', 'RO', 'Orange Romania S.A.', '5G', 'global_109'),
('Saudi Arabia', 'SA', 'Mobily (Etihad Etisalat Company)', '5G', 'global_109'),
('Senegal', 'SN', 'SONATEL', '4G', 'global_109'),
('Senegal', 'SN', 'Expresso Senegal SA', '4G', 'global_109'),
('Serbia', 'RS', 'A1', '4G', 'global_109'),
-- Seychelles to Sri Lanka
('Seychelles', 'SC', 'Cable & Wireless (Seychelles)', '4G', 'global_109'),
('Sierra Leone', 'SL', 'Airtel Sierra Leone (former: Zain / Celtel Ltd.)', '4G', 'global_109'),
('Singapore', 'SG', 'SingTel', '5G', 'global_109'),
('Singapore', 'SG', 'Starhub', '5G', 'global_109'),
('Slovakia', 'SK', 'Orange Slovensko a.s.', '4G', 'global_109'),
('Slovakia', 'SK', 'O2 Slovakia, s.r.o.', '4G', 'global_109'),
('Slovenia', 'SI', 'A1 Slovenija, d.d', '5G', 'global_109'),
('Slovenia', 'SI', 'Telemach d.o.o.', '5G', 'global_109'),
('South Africa', 'ZA', 'Vodacom Pty Ltd.', '4G', 'global_109'),
('South Korea', 'KR', 'KT Corporation', '4G', 'global_109'),
('South Korea', 'KR', 'SK Telecom', '5G', 'global_109'),
('Spain', 'ES', 'Vodafone', '4G', 'global_109'),
('Spain', 'ES', 'Orange', '5G', 'global_109'),
('Spain', 'ES', 'Movistar', '5G', 'global_109'),
('Spain', 'ES', 'Xfera Moviles S.A. (Yoigo)', '4G', 'global_109'),
('Sri Lanka', 'LK', 'Hutchison Telecom Sri Lanka', '4G', 'global_109'),
-- Suriname to Turkey
('Suriname', 'SR', 'Digicel Suriname', '4G', 'global_109'),
('Sweden', 'SE', 'Hi3G Access AB (3)', '5G', 'global_109'),
('Switzerland', 'CH', 'Sunrise Communications AG', '5G', 'global_109'),
('Switzerland', 'CH', 'Salt', '5G', 'global_109'),
('Taiwan', 'TW', 'Chunghwa Telecom Mobile', '5G', 'global_109'),
('Tanzania', 'TZ', 'Airtel Tanzania Ltd. (former: Zain/Celtel)', '4G', 'global_109'),
('Thailand', 'TH', 'Advance Wireless Network Company Limited', '5G', 'global_109'),
('Timor-Leste', 'TL', 'Viettel Timor Leste', '4G', 'global_109'),
('Trinidad and Tobago', 'TT', 'Digicel Trinidad & Tobago Ltd.', '4G', 'global_109'),
('Tunisia', 'TN', 'Orange Tunisie, SA', '4G', 'global_109'),
('Turkey', 'TR', 'AVEA', '5G', 'global_109')
ON CONFLICT (country_name, carrier_name, network_type, region_preset) DO NOTHING;
