-- Insert Asia 13 carriers
INSERT INTO public.country_carriers (country_name, country_code, carrier_name, network_type, region_preset, source)
VALUES
  ('Thailand', 'TH', 'Real Future (Truemove)', '5G', 'asia_13', 'manual'),
  ('Indonesia', 'ID', 'XL (Excelcom)', '4G', 'asia_13', 'manual'),
  ('Indonesia', 'ID', 'Indosat', '4G', 'asia_13', 'manual'),
  ('Indonesia', 'ID', 'Telkomsel', '4G', 'asia_13', 'manual'),
  ('Singapore', 'SG', 'Singtel', '5G', 'asia_13', 'manual'),
  ('Taiwan', 'TW', 'Chunghwa', '4G', 'asia_13', 'manual'),
  ('Japan', 'JP', 'KDDI', '5G', 'asia_13', 'manual'),
  ('Japan', 'JP', 'Softbank', '5G', 'asia_13', 'manual'),
  ('Japan', 'JP', 'Docomo', '5G', 'asia_13', 'manual'),
  ('Laos', 'LA', 'LTC', '5G', 'asia_13', 'manual'),
  ('China', 'CN', 'CMCC', '5G', 'asia_13', 'manual'),
  ('Cambodia', 'KH', 'CamGSM', '4G', 'asia_13', 'manual'),
  ('Malaysia', 'MY', 'Maxis', '4G', 'asia_13', 'manual'),
  ('Malaysia', 'MY', 'Celcom', '4G', 'asia_13', 'manual'),
  ('Malaysia', 'MY', 'Digi', '4G', 'asia_13', 'manual'),
  ('Philippines', 'PH', 'Smart', '5G', 'asia_13', 'manual'),
  ('Philippines', 'PH', 'Globe', '5G', 'asia_13', 'manual'),
  ('Hong Kong', 'HK', 'CMHK', '4G', 'asia_13', 'manual'),
  ('Macau', 'MO', 'CTM', '5G', 'asia_13', 'manual'),
  ('Vietnam', 'VN', 'Vinaphone', '5G', 'asia_13', 'manual'),
  ('Vietnam', 'VN', 'Mobifone', '5G', 'asia_13', 'manual'),
  ('Vietnam', 'VN', 'Viettel', '5G', 'asia_13', 'manual'),
  -- Asia 3 carriers
  ('Thailand', 'TH', 'Real Future (Truemove)', '5G', 'asia_3', 'manual'),
  ('Singapore', 'SG', 'Singtel', '5G', 'asia_3', 'manual'),
  ('Malaysia', 'MY', 'Maxis', '4G', 'asia_3', 'manual'),
  ('Malaysia', 'MY', 'Celcom', '4G', 'asia_3', 'manual'),
  ('Malaysia', 'MY', 'Digi', '4G', 'asia_3', 'manual'),
  -- Asia 8 carriers
  ('Hong Kong', 'HK', 'CMHK', '4G', 'asia_8', 'manual'),
  ('Macau', 'MO', 'CTM', '5G', 'asia_8', 'manual'),
  ('Singapore', 'SG', 'Singtel', '5G', 'asia_8', 'manual'),
  ('Malaysia', 'MY', 'Maxis', '4G', 'asia_8', 'manual'),
  ('Malaysia', 'MY', 'Celcom', '4G', 'asia_8', 'manual'),
  ('Malaysia', 'MY', 'Digi', '4G', 'asia_8', 'manual'),
  ('Thailand', 'TH', 'Real Future (Truemove)', '5G', 'asia_8', 'manual'),
  ('Indonesia', 'ID', 'XL (Excelcom)', '4G', 'asia_8', 'manual'),
  ('Indonesia', 'ID', 'Indosat', '4G', 'asia_8', 'manual'),
  ('Indonesia', 'ID', 'Telkomsel', '4G', 'asia_8', 'manual'),
  ('Vietnam', 'VN', 'Vinaphone', '5G', 'asia_8', 'manual'),
  ('Vietnam', 'VN', 'Mobifone', '5G', 'asia_8', 'manual'),
  ('Vietnam', 'VN', 'Viettel', '5G', 'asia_8', 'manual'),
  ('Cambodia', 'KH', 'CamGSM', '4G', 'asia_8', 'manual')
ON CONFLICT DO NOTHING;