-- Sync all Help Center articles to kb_articles for AI chatbot
-- First, clear existing auto-imported articles (keep manually added ones)
DELETE FROM kb_articles WHERE category IN ('troubleshoot', 'esim-data-plan', 'payments-billing', 'account', 'about-esim', 'faq', 'getting-started', 'installation');

-- Insert all Help Center articles (English versions)

-- Troubleshoot articles (English)
INSERT INTO kb_articles (title, content, category, language, is_published, is_internal, tags) VALUES
('My eSIM is not activating', 'Steps to troubleshoot when your eSIM won''t activate. Check device compatibility - make sure your device supports eSIM and is carrier unlocked. Check your internet connection - eSIM activation requires stable Wi-Fi or mobile data. Restart your device - turn off completely, wait 30 seconds, turn back on. Contact support if issues persist with order number and device model.', 'troubleshoot', 'en', true, false, ARRAY['activation', 'not working', 'troubleshoot']),
('I have no internet connection', 'What to do when your eSIM has no data connection. Enable data roaming in Settings > Cellular. Select eSIM for data in cellular settings. Check network coverage in your area. Try manual network selection if automatic doesn''t work.', 'troubleshoot', 'en', true, false, ARRAY['no internet', 'connection', 'data roaming']),
('My internet speed is slow', 'Tips to improve your eSIM data speed. Check your data limit in account dashboard. Network congestion varies by time and location. Select preferred network type (5G/LTE) in settings for faster speeds.', 'troubleshoot', 'en', true, false, ARRAY['slow speed', 'internet speed', 'network']),
('I cannot scan the QR code', 'What to do if you have trouble scanning your eSIM QR code. Display QR on another device. Ensure good lighting. Try manual installation with SM-DP+ address and activation code from email.', 'troubleshoot', 'en', true, false, ARRAY['QR code', 'scan', 'installation']),
('eSIM Stuck at Activating', 'What to do when your eSIM is stuck in activating status. Normally takes 1-5 minutes. Check internet connection. Restart device. Check cellular settings. Contact support if stuck more than 30 minutes.', 'troubleshoot', 'en', true, false, ARRAY['stuck', 'activating', 'pending']),
('Cellular Plans Cannot Be Added Error', 'How to fix the "Cellular Plans from This Carrier Cannot Be Added" error. Check if device is carrier-locked. Verify QR code hasn''t been used. Update software. Try manual installation.', 'troubleshoot', 'en', true, false, ARRAY['error', 'cannot add', 'carrier locked']),
('What are the APN Settings for my eSIM?', 'Understanding and configuring APN settings. Most Mobile11 eSIMs configure APN automatically. If needed, enter APN settings from order email manually in cellular settings.', 'troubleshoot', 'en', true, false, ARRAY['APN', 'settings', 'configuration']),
('This Code Is No Longer Valid Error', 'What to do when you see the code is no longer valid message. QR code may already be used (each works once). Check if eSIM is already installed. Contact support for replacement if deleted.', 'troubleshoot', 'en', true, false, ARRAY['invalid code', 'QR code', 'error']),
('eSIM Not Showing in Settings', 'Troubleshoot when eSIM doesn''t appear in device settings. Check if installation completed. Restart device. Go to Settings > Cellular to find eSIM profile.', 'troubleshoot', 'en', true, false, ARRAY['not showing', 'settings', 'missing']),
('Data Not Working After Landing', 'Fix data issues when arriving at destination. Enable data roaming. Select eSIM for mobile data. Wait 5-10 minutes for network registration. Try manual network selection.', 'troubleshoot', 'en', true, false, ARRAY['landing', 'arrival', 'data not working']),
('How to Delete eSIM from Device', 'Steps to remove eSIM profile from your device. iPhone: Settings > Cellular > tap eSIM > Remove Cellular Plan. Android: Settings > Connections > SIM Manager > delete profile. Warning: deleted eSIM cannot be reinstalled with same QR code.', 'troubleshoot', 'en', true, false, ARRAY['delete', 'remove', 'uninstall']),
('eSIM Working but No Signal Bars', 'Troubleshoot when eSIM is active but shows no signal. This may be normal if using eSIM only for data. Check data connection works. Try different network.', 'troubleshoot', 'en', true, false, ARRAY['no signal', 'signal bars', 'connection']),
('Cannot Make Calls with eSIM', 'Mobile11 eSIMs are data-only. They do not support voice calls or SMS. Keep your regular SIM for calls. Use WhatsApp, LINE, or other VoIP apps for calls over data.', 'troubleshoot', 'en', true, false, ARRAY['calls', 'voice', 'SMS', 'data only']),
('eSIM Data Depleted Before Expected', 'Track your data usage in account dashboard. Check for background app updates. Some apps consume data quickly (video streaming, cloud backups). Consider top-up or larger plan.', 'troubleshoot', 'en', true, false, ARRAY['data usage', 'depleted', 'running out']),

-- eSIM Data Plan articles (English)
('How to Top Up Your eSIM', 'Learn how to add more data to your existing eSIM. Top-up allows adding data without reinstalling. Log into account, go to My eSIMs, select eSIM, click Top Up. Data added automatically within 5-15 minutes.', 'esim-data-plan', 'en', true, false, ARRAY['top up', 'add data', 'reload']),
('Understanding Mobile11 Plan Types', 'Learn about Day Pass, Max Speed, and Limitless plans. All plans are truly unlimited - you are never cut off. Day Pass: daily high-speed allowance resets every 24 hours, then 1 Mbps fallback. Max Speed: bulk high-speed data upfront, then 384 Kbps fallback. Limitless: unlimited data at maximum speeds with no throttling.', 'esim-data-plan', 'en', true, false, ARRAY['plan types', 'day pass', 'max speed', 'limitless', 'unlimited']),
('Regional vs Local eSIM', 'Compare regional and local eSIM options. Local eSIM: best value per GB, optimal for single country. Regional eSIM: one eSIM for multiple countries, convenient for multi-destination trips.', 'esim-data-plan', 'en', true, false, ARRAY['regional', 'local', 'multi-country']),
('When Does My eSIM Validity Start?', 'Validity starts when you first connect to a network at your destination, not when you install. Install before travel, activate when you arrive. Check specific plan terms for details.', 'esim-data-plan', 'en', true, false, ARRAY['validity', 'start date', 'expiry']),
('How to Check Data Usage', 'Check your data usage in the Mobile11 account dashboard under My eSIMs. Also check in device settings: iPhone Settings > Cellular, Android Settings > Data Usage.', 'esim-data-plan', 'en', true, false, ARRAY['data usage', 'check balance', 'remaining data']),
('Can I Use eSIM as Hotspot?', 'Yes, most Mobile11 eSIMs support hotspot/tethering. Enable in Settings > Personal Hotspot (iPhone) or Settings > Hotspot (Android). Note: hotspot uses data faster.', 'esim-data-plan', 'en', true, false, ARRAY['hotspot', 'tethering', 'share data']),
('eSIM Coverage and Networks', 'Mobile11 works in 150+ countries. Each plan lists covered countries and partner networks. Best coverage with local carrier partners for each destination.', 'esim-data-plan', 'en', true, false, ARRAY['coverage', 'networks', 'countries']),
('What Speed Can I Expect?', 'Speeds depend on plan type and local network. Limitless: maximum network speed (LTE/5G). Day Pass after limit: 1 Mbps. Max Speed after limit: 384 Kbps. Actual speeds vary by location and congestion.', 'esim-data-plan', 'en', true, false, ARRAY['speed', 'LTE', '5G', 'network speed']),
('Extending Your eSIM Plan', 'Extend validity or add data by purchasing a top-up. Log into account, select your eSIM, choose add-on package. Some plans support extension, others require new purchase.', 'esim-data-plan', 'en', true, false, ARRAY['extend', 'renewal', 'add time']),

-- Payments and Billing articles (English)
('Payment Methods Accepted', 'Mobile11 accepts credit cards (Visa, Mastercard, Amex), debit cards, PayPal, Google Pay, Apple Pay, and local payment methods including PromptPay in Thailand.', 'payments-billing', 'en', true, false, ARRAY['payment methods', 'credit card', 'PayPal']),
('Refund Policy', 'Refunds available within 30 days if eSIM has not been installed/activated. Once QR code is scanned, the eSIM cannot be refunded. Contact support for refund requests with order number.', 'payments-billing', 'en', true, false, ARRAY['refund', 'return', 'money back']),
('How to Get Invoice', 'Access invoices in your account dashboard under Order History. Click on any order to view and download PDF invoice. For additional billing needs, contact support.', 'payments-billing', 'en', true, false, ARRAY['invoice', 'receipt', 'billing']),
('Currency and Pricing', 'Prices shown in USD by default. Currency can be changed to THB and others. Final charge in your local currency depends on your card issuer''s exchange rate.', 'payments-billing', 'en', true, false, ARRAY['currency', 'pricing', 'exchange rate']),
('Payment Failed', 'If payment fails, check card details, ensure sufficient funds, try different payment method. Contact your bank if card is declined. Try again or use alternative payment.', 'payments-billing', 'en', true, false, ARRAY['payment failed', 'declined', 'error']),
('Promo Codes and Discounts', 'Enter promo code at checkout in the discount field. Promo codes cannot be combined with referral discounts. Each promo code has specific terms and validity period.', 'payments-billing', 'en', true, false, ARRAY['promo code', 'discount', 'coupon']),

-- Account articles (English)
('How to Create Account', 'Create account on Mobile11 website or app. Enter email and password, or sign up with Google/LINE. Verify email to complete registration. Account required for loyalty program and order management.', 'account', 'en', true, false, ARRAY['create account', 'sign up', 'register']),
('Forgot Password', 'Reset password via login page. Click "Forgot Password", enter email, check inbox for reset link. Link valid for 24 hours. Contact support if issues persist.', 'account', 'en', true, false, ARRAY['forgot password', 'reset', 'login']),
('Update Account Information', 'Update profile in account settings. Change name, email, phone number. For email change, verification required for new email address.', 'account', 'en', true, false, ARRAY['update account', 'profile', 'settings']),
('What is Mobile11 Money?', 'Mobile11 Money is our cashback reward currency. Earn 5-15% back on purchases based on loyalty tier. Use at checkout to reduce order total. 1 Mobile11 Money = $1 USD. Valid for 1 year (resets with each purchase).', 'account', 'en', true, false, ARRAY['mobile11 money', 'cashback', 'rewards']),
('Mobile11 Loyalty Program', 'Three-tier loyalty program: Explorer (5% cashback), Silver Explorer (10% at $100 spent), Gold Explorer (15% at $500 spent). Automatic enrollment with first purchase. Tiers never expire.', 'account', 'en', true, false, ARRAY['loyalty', 'tiers', 'cashback', 'rewards']),
('How to Use Mobile11 Money', 'Apply Mobile11 Money at checkout. Enter amount to use or click "Use All". Remaining balance shown in account. Can combine with regular payment but not with promo codes.', 'account', 'en', true, false, ARRAY['use rewards', 'redeem', 'checkout']),
('Referral Program', 'Refer friends and earn $5.00 Mobile11 Money when they make their first qualifying purchase (minimum $10 order). Share your unique referral link from account dashboard. Friends also get a $5.00 welcome discount.', 'account', 'en', true, false, ARRAY['referral', 'invite friends', 'earn rewards']),
('View Order History', 'Access order history in account dashboard. See all past orders, download eSIM QR codes, check order status, and access invoices.', 'account', 'en', true, false, ARRAY['order history', 'past orders', 'purchases']),
('Account Security', 'Keep account secure with strong password. Enable two-factor authentication if available. Never share login credentials. Report suspicious activity to support.', 'account', 'en', true, false, ARRAY['security', 'password', 'protection']),

-- About eSIM / FAQ articles (English)
('What is an eSIM?', 'An eSIM (embedded SIM) is a digital SIM that allows you to activate a cellular plan without using a physical SIM card. It''s built into your device and can be programmed with carrier information remotely. Key benefits: instant activation, no physical SIM to lose, can store multiple profiles, environmentally friendly.', 'faq', 'en', true, false, ARRAY['what is esim', 'definition', 'digital SIM']),
('Is my phone eSIM compatible?', 'Most modern smartphones support eSIM. Compatible iPhones: XS, XR and later, SE 2nd gen and later. Compatible Android: Samsung Galaxy S20+, Google Pixel 3+, and many others. Check Settings > About > look for EID number to verify. Device must be carrier-unlocked.', 'faq', 'en', true, false, ARRAY['compatible', 'supported phones', 'device check']),
('How long does eSIM activation take?', 'QR code delivered instantly via email after purchase. Installation takes 1-2 minutes. Network connection at destination: 1-5 minutes. Tip: Install before travel, activate when you arrive.', 'faq', 'en', true, false, ARRAY['activation time', 'how long', 'instant']),
('Can I keep my phone number?', 'Yes! Use dual SIM setup - your physical SIM keeps your home number for calls/SMS, Mobile11 eSIM provides data abroad. Both work simultaneously. Set eSIM for mobile data in settings.', 'faq', 'en', true, false, ARRAY['keep number', 'dual SIM', 'phone number']),
('eSIM vs physical SIM: What''s the difference?', 'eSIM: digital, instant activation via QR code, no shipping, cannot lose, multiple profiles, newer phones only. Physical SIM: plastic card, insert in phone, shipping required, easy to lose, one per slot, works on most phones.', 'faq', 'en', true, false, ARRAY['esim vs sim', 'comparison', 'difference']),
('How do I contact Mobile11 support?', 'Live chat on website (fastest), email support@mobile11.com, LINE @mobile11. Support available 24/7 in English and Thai. Include order number for faster assistance.', 'faq', 'en', true, false, ARRAY['contact support', 'help', 'customer service']),
('Can I use eSIM in multiple countries?', 'Yes! Regional and global eSIM plans work across multiple countries. Check coverage details on each plan. Single eSIM for entire multi-country trip.', 'faq', 'en', true, false, ARRAY['multiple countries', 'regional', 'global']),
('How do I activate my eSIM?', 'After purchase, receive QR code via email. Scan with phone camera or go to Settings > Cellular > Add eSIM. Follow on-screen instructions. Takes less than 5 minutes.', 'faq', 'en', true, false, ARRAY['activate', 'install', 'QR code']),

-- FAQ from landing page (English)
('What if I need help with my eSIM?', 'Our support team is available 24/7 via chat, email, or LINE. We offer support in both English and Thai to assist you with any questions or issues.', 'faq', 'en', true, false, ARRAY['help', 'support', '24/7']);

-- Insert Thai versions

-- Troubleshoot articles (Thai)
INSERT INTO kb_articles (title, content, category, language, is_published, is_internal, tags) VALUES
('eSIM ของฉันไม่ทำงาน', 'ขั้นตอนการแก้ปัญหาเมื่อ eSIM ไม่ทำงาน ตรวจสอบความเข้ากันได้ของอุปกรณ์ - ตรวจสอบว่าอุปกรณ์รองรับ eSIM และปลดล็อคจากผู้ให้บริการ ตรวจสอบการเชื่อมต่ออินเทอร์เน็ต - ต้องใช้ Wi-Fi หรือข้อมูลมือถือที่เสถียร รีสตาร์ทอุปกรณ์ - ปิดเครื่อง รอ 30 วินาที เปิดใหม่ ติดต่อฝ่ายสนับสนุนหากปัญหายังคงอยู่', 'troubleshoot', 'th', true, false, ARRAY['เปิดใช้งาน', 'ไม่ทำงาน', 'แก้ปัญหา']),
('ไม่มีการเชื่อมต่ออินเทอร์เน็ต', 'จะทำอย่างไรเมื่อ eSIM ไม่มีการเชื่อมต่อข้อมูล เปิดโรมมิ่งข้อมูลในตั้งค่า > เซลลูลาร์ เลือก eSIM สำหรับข้อมูลในการตั้งค่า ตรวจสอบพื้นที่ครอบคลุมเครือข่าย ลองเลือกเครือข่ายด้วยตนเอง', 'troubleshoot', 'th', true, false, ARRAY['ไม่มีอินเทอร์เน็ต', 'เชื่อมต่อ', 'โรมมิ่ง']),
('ความเร็วอินเทอร์เน็ตช้า', 'เคล็ดลับเพื่อปรับปรุงความเร็ว eSIM ตรวจสอบขีดจำกัดข้อมูลในแดชบอร์ด ความแออัดของเครือข่ายขึ้นอยู่กับเวลาและสถานที่ เลือกประเภทเครือข่ายที่ต้องการ (5G/LTE) ในการตั้งค่า', 'troubleshoot', 'th', true, false, ARRAY['ช้า', 'ความเร็ว', 'เครือข่าย']),
('ไม่สามารถสแกน QR code ได้', 'จะทำอย่างไรถ้าไม่สามารถสแกน QR code eSIM ได้ แสดง QR บนอุปกรณ์อื่น ตรวจสอบแสงสว่าง ลองติดตั้งด้วยตนเองด้วยที่อยู่ SM-DP+ และรหัสเปิดใช้งานจากอีเมล', 'troubleshoot', 'th', true, false, ARRAY['QR code', 'สแกน', 'ติดตั้ง']),
('eSIM ค้างอยู่ที่กำลังเปิดใช้งาน', 'จะทำอย่างไรเมื่อ eSIM ค้างในสถานะกำลังเปิดใช้งาน โดยปกติใช้เวลา 1-5 นาที ตรวจสอบการเชื่อมต่ออินเทอร์เน็ต รีสตาร์ทอุปกรณ์ ตรวจสอบการตั้งค่าเซลลูลาร์ ติดต่อฝ่ายสนับสนุนหากค้างนานกว่า 30 นาที', 'troubleshoot', 'th', true, false, ARRAY['ค้าง', 'กำลังเปิดใช้งาน', 'รอ']),
('ข้อผิดพลาด "ไม่สามารถเพิ่มแผนเซลลูลาร์"', 'วิธีแก้ไขข้อผิดพลาด "ไม่สามารถเพิ่มแผนเซลลูลาร์จากผู้ให้บริการนี้" ตรวจสอบว่าอุปกรณ์ถูกล็อคกับผู้ให้บริการหรือไม่ ยืนยันว่า QR code ไม่เคยถูกใช้ อัปเดตซอฟต์แวร์ ลองติดตั้งด้วยตนเอง', 'troubleshoot', 'th', true, false, ARRAY['ข้อผิดพลาด', 'ไม่สามารถเพิ่ม', 'ล็อค']),

-- eSIM Data Plan articles (Thai)
('วิธีเติมเงิน eSIM ของคุณ', 'เรียนรู้วิธีเพิ่มข้อมูลให้กับ eSIM ที่มีอยู่ การเติมเงินช่วยเพิ่มข้อมูลโดยไม่ต้องติดตั้งใหม่ เข้าสู่ระบบบัญชี ไปที่ eSIM ของฉัน เลือก eSIM คลิกเติมเงิน ข้อมูลเพิ่มอัตโนมัติภายใน 5-15 นาที', 'esim-data-plan', 'th', true, false, ARRAY['เติมเงิน', 'เพิ่มข้อมูล', 'รีโหลด']),
('ทำความเข้าใจประเภทแพ็คเกจ Mobile11', 'เรียนรู้เกี่ยวกับแพ็คเกจ Day Pass, Max Speed และ Limitless ทุกแพ็คเกจไม่จำกัดจริง - คุณจะไม่ถูกตัดเลย Day Pass: โควต้าความเร็วสูงรายวันรีเซ็ตทุก 24 ชั่วโมง จากนั้น 1 Mbps Max Speed: ข้อมูลความเร็วสูงล่วงหน้า จากนั้น 384 Kbps Limitless: ไม่จำกัดที่ความเร็วสูงสุดไม่มีการลดความเร็ว', 'esim-data-plan', 'th', true, false, ARRAY['ประเภทแพ็คเกจ', 'day pass', 'limitless', 'ไม่จำกัด']),
('eSIM ภูมิภาค vs ท้องถิ่น', 'เปรียบเทียบตัวเลือก eSIM ภูมิภาคและท้องถิ่น eSIM ท้องถิ่น: คุ้มค่าที่สุดต่อ GB เหมาะสำหรับประเทศเดียว eSIM ภูมิภาค: eSIM เดียวสำหรับหลายประเทศ สะดวกสำหรับเดินทางหลายจุดหมาย', 'esim-data-plan', 'th', true, false, ARRAY['ภูมิภาค', 'ท้องถิ่น', 'หลายประเทศ']),
('อายุ eSIM เริ่มเมื่อไหร่?', 'อายุเริ่มเมื่อคุณเชื่อมต่อเครือข่ายครั้งแรกที่ปลายทาง ไม่ใช่เมื่อติดตั้ง ติดตั้งก่อนเดินทาง เปิดใช้งานเมื่อถึง ตรวจสอบเงื่อนไขแพ็คเกจสำหรับรายละเอียด', 'esim-data-plan', 'th', true, false, ARRAY['อายุ', 'วันเริ่ม', 'หมดอายุ']),
('วิธีตรวจสอบการใช้ข้อมูล', 'ตรวจสอบการใช้ข้อมูลในแดชบอร์ดบัญชี Mobile11 ภายใต้ eSIM ของฉัน ตรวจสอบในการตั้งค่าอุปกรณ์: iPhone ตั้งค่า > เซลลูลาร์, Android ตั้งค่า > การใช้ข้อมูล', 'esim-data-plan', 'th', true, false, ARRAY['การใช้ข้อมูล', 'ตรวจสอบยอด', 'ข้อมูลเหลือ']),

-- Payments and Billing articles (Thai)
('วิธีการชำระเงินที่รับ', 'Mobile11 รับบัตรเครดิต (Visa, Mastercard, Amex) บัตรเดบิต PayPal Google Pay Apple Pay และวิธีการชำระเงินท้องถิ่นรวมถึง PromptPay ในไทย', 'payments-billing', 'th', true, false, ARRAY['วิธีชำระเงิน', 'บัตรเครดิต', 'PayPal']),
('นโยบายการคืนเงิน', 'คืนเงินได้ภายใน 30 วันหาก eSIM ยังไม่ได้ติดตั้ง/เปิดใช้งาน เมื่อสแกน QR code แล้ว eSIM ไม่สามารถคืนเงินได้ ติดต่อฝ่ายสนับสนุนพร้อมหมายเลขคำสั่งซื้อ', 'payments-billing', 'th', true, false, ARRAY['คืนเงิน', 'ขอเงินคืน', 'นโยบาย']),
('วิธีรับใบแจ้งหนี้', 'เข้าถึงใบแจ้งหนี้ในแดชบอร์ดบัญชีภายใต้ประวัติคำสั่งซื้อ คลิกคำสั่งซื้อเพื่อดูและดาวน์โหลดใบแจ้งหนี้ PDF ติดต่อฝ่ายสนับสนุนสำหรับความต้องการเพิ่มเติม', 'payments-billing', 'th', true, false, ARRAY['ใบแจ้งหนี้', 'ใบเสร็จ', 'บิล']),
('สกุลเงินและราคา', 'ราคาแสดงเป็น USD โดยเริ่มต้น สกุลเงินสามารถเปลี่ยนเป็น THB และอื่นๆ ค่าใช้จ่ายสุดท้ายในสกุลเงินท้องถิ่นขึ้นอยู่กับอัตราแลกเปลี่ยนของผู้ออกบัตร', 'payments-billing', 'th', true, false, ARRAY['สกุลเงิน', 'ราคา', 'อัตราแลกเปลี่ยน']),
('การชำระเงินล้มเหลว', 'หากการชำระเงินล้มเหลว ตรวจสอบรายละเอียดบัตร ยอดเงินเพียงพอ ลองวิธีชำระเงินอื่น ติดต่อธนาคารหากบัตรถูกปฏิเสธ ลองอีกครั้งหรือใช้การชำระเงินทางเลือก', 'payments-billing', 'th', true, false, ARRAY['ชำระเงินล้มเหลว', 'ปฏิเสธ', 'ข้อผิดพลาด']),
('โปรโมโค้ดและส่วนลด', 'ใส่โปรโมโค้ดที่ checkout ในช่องส่วนลด โปรโมโค้ดไม่สามารถใช้ร่วมกับส่วนลดการแนะนำ แต่ละโปรโมโค้ดมีเงื่อนไขและระยะเวลาเฉพาะ', 'payments-billing', 'th', true, false, ARRAY['โปรโมโค้ด', 'ส่วนลด', 'คูปอง']),

-- Account articles (Thai)
('วิธีสร้างบัญชี', 'สร้างบัญชีบนเว็บไซต์หรือแอป Mobile11 ใส่อีเมลและรหัสผ่าน หรือลงทะเบียนด้วย Google/LINE ยืนยันอีเมลเพื่อเสร็จสิ้นการลงทะเบียน ต้องมีบัญชีสำหรับโปรแกรมสะสมคะแนนและจัดการคำสั่งซื้อ', 'account', 'th', true, false, ARRAY['สร้างบัญชี', 'ลงทะเบียน', 'สมัคร']),
('ลืมรหัสผ่าน', 'รีเซ็ตรหัสผ่านผ่านหน้าเข้าสู่ระบบ คลิก "ลืมรหัสผ่าน" ใส่อีเมล ตรวจสอบกล่องจดหมายสำหรับลิงก์รีเซ็ต ลิงก์ใช้ได้ 24 ชั่วโมง ติดต่อฝ่ายสนับสนุนหากมีปัญหา', 'account', 'th', true, false, ARRAY['ลืมรหัสผ่าน', 'รีเซ็ต', 'เข้าสู่ระบบ']),
('Mobile11 Money คืออะไร?', 'Mobile11 Money คือสกุลเงินรางวัลเงินคืนของเรา รับ 5-15% คืนตามระดับสมาชิก ใช้ที่ checkout เพื่อลดยอดรวม 1 Mobile11 Money = $1 USD มีอายุ 1 ปี (รีเซ็ตทุกการซื้อ)', 'account', 'th', true, false, ARRAY['mobile11 money', 'เงินคืน', 'รางวัล']),
('โปรแกรมสะสมคะแนน Mobile11', 'โปรแกรมสะสมคะแนน 3 ระดับ: Explorer (เงินคืน 5%), Silver Explorer (10% ที่ $100), Gold Explorer (15% ที่ $500) ลงทะเบียนอัตโนมัติเมื่อซื้อครั้งแรก ระดับไม่หมดอายุ', 'account', 'th', true, false, ARRAY['สะสมคะแนน', 'ระดับ', 'เงินคืน', 'รางวัล']),
('วิธีใช้ Mobile11 Money', 'ใช้ Mobile11 Money ที่ checkout ใส่จำนวนที่ต้องการใช้หรือคลิก "ใช้ทั้งหมด" ยอดเหลือแสดงในบัญชี สามารถรวมกับการชำระเงินปกติแต่ไม่สามารถใช้กับโปรโมโค้ด', 'account', 'th', true, false, ARRAY['ใช้รางวัล', 'แลก', 'checkout']),
('โปรแกรมแนะนำเพื่อน', 'แนะนำเพื่อนและรับ $5.00 Mobile11 Money เมื่อพวกเขาสั่งซื้อครั้งแรก (ขั้นต่ำ $10) แชร์ลิงก์แนะนำของคุณจากแดชบอร์ดบัญชี เพื่อนได้รับส่วนลดต้อนรับ $5.00 ด้วย', 'account', 'th', true, false, ARRAY['แนะนำเพื่อน', 'เชิญเพื่อน', 'รับรางวัล']),
('ดูประวัติคำสั่งซื้อ', 'เข้าถึงประวัติคำสั่งซื้อในแดชบอร์ดบัญชี ดูคำสั่งซื้อที่ผ่านมา ดาวน์โหลด QR code eSIM ตรวจสอบสถานะคำสั่งซื้อ และเข้าถึงใบแจ้งหนี้', 'account', 'th', true, false, ARRAY['ประวัติ', 'คำสั่งซื้อ', 'การซื้อ']),

-- FAQ articles (Thai)
('eSIM คืออะไร?', 'eSIM (embedded SIM) คือ SIM ดิจิทัลที่ช่วยให้คุณเปิดใช้งานแผนเซลลูลาร์โดยไม่ต้องใช้ SIM การ์ดจริง มันถูกสร้างในอุปกรณ์และสามารถโปรแกรมด้วยข้อมูลผู้ให้บริการทางไกล ประโยชน์หลัก: เปิดใช้งานทันที ไม่มี SIM จริงให้หาย เก็บหลายโปรไฟล์ได้ เป็นมิตรกับสิ่งแวดล้อม', 'faq', 'th', true, false, ARRAY['eSIM คืออะไร', 'ความหมาย', 'SIM ดิจิทัล']),
('โทรศัพท์ของฉันรองรับ eSIM ไหม?', 'สมาร์ทโฟนรุ่นใหม่ส่วนใหญ่รองรับ eSIM iPhone ที่รองรับ: XS, XR และใหม่กว่า, SE รุ่นที่ 2 และใหม่กว่า Android ที่รองรับ: Samsung Galaxy S20+, Google Pixel 3+ และอื่นๆ ตรวจสอบ ตั้งค่า > เกี่ยวกับ > มองหาหมายเลข EID เพื่อยืนยัน อุปกรณ์ต้องปลดล็อคจากผู้ให้บริการ', 'faq', 'th', true, false, ARRAY['รองรับ', 'โทรศัพท์ที่รองรับ', 'ตรวจสอบอุปกรณ์']),
('การเปิดใช้งาน eSIM ใช้เวลานานแค่ไหน?', 'QR code ส่งทันทีทางอีเมลหลังซื้อ การติดตั้งใช้เวลา 1-2 นาที การเชื่อมต่อเครือข่ายที่ปลายทาง: 1-5 นาที เคล็ดลับ: ติดตั้งก่อนเดินทาง เปิดใช้งานเมื่อถึง', 'faq', 'th', true, false, ARRAY['เวลาเปิดใช้งาน', 'นานแค่ไหน', 'ทันที']),
('ฉันสามารถใช้หมายเลขโทรศัพท์เดิมได้ไหม?', 'ได้! ใช้ dual SIM - SIM จริงเก็บหมายเลขบ้านสำหรับโทร/SMS, Mobile11 eSIM ให้ข้อมูลในต่างประเทศ ทั้งสองทำงานพร้อมกัน ตั้ง eSIM สำหรับข้อมูลมือถือในการตั้งค่า', 'faq', 'th', true, false, ARRAY['เก็บหมายเลข', 'dual SIM', 'หมายเลขโทรศัพท์']),
('eSIM vs SIM จริง: ต่างกันอย่างไร?', 'eSIM: ดิจิทัล เปิดใช้งานทันทีผ่าน QR code ไม่ต้องส่ง หายไม่ได้ หลายโปรไฟล์ เฉพาะโทรศัพท์ใหม่ SIM จริง: การ์ดพลาสติก ใส่ในโทรศัพท์ ต้องส่ง หายง่าย หนึ่งต่อช่อง ใช้ได้กับโทรศัพท์ส่วนใหญ่', 'faq', 'th', true, false, ARRAY['esim vs sim', 'เปรียบเทียบ', 'ต่างกัน']),
('ฉันจะติดต่อฝ่ายสนับสนุน Mobile11 ได้อย่างไร?', 'แชทสดบนเว็บไซต์ (เร็วที่สุด) อีเมล support@mobile11.com LINE @mobile11 ฝ่ายสนับสนุนพร้อมให้บริการ 24/7 ภาษาไทยและอังกฤษ แนบหมายเลขคำสั่งซื้อเพื่อรับความช่วยเหลือเร็วขึ้น', 'faq', 'th', true, false, ARRAY['ติดต่อฝ่ายสนับสนุน', 'ช่วยเหลือ', 'บริการลูกค้า']),
('ฉันสามารถใช้ eSIM ในหลายประเทศได้ไหม?', 'ได้! แพ็คเกจ eSIM ภูมิภาคและทั่วโลกใช้งานได้ในหลายประเทศ ตรวจสอบรายละเอียดความครอบคลุมในแต่ละแพ็คเกจ eSIM เดียวสำหรับการเดินทางหลายประเทศ', 'faq', 'th', true, false, ARRAY['หลายประเทศ', 'ภูมิภาค', 'ทั่วโลก']),
('ฉันเปิดใช้งาน eSIM อย่างไร?', 'หลังซื้อ รับ QR code ทางอีเมล สแกนด้วยกล้องโทรศัพท์หรือไปที่ ตั้งค่า > เซลลูลาร์ > เพิ่ม eSIM ทำตามคำแนะนำบนหน้าจอ ใช้เวลาไม่ถึง 5 นาที', 'faq', 'th', true, false, ARRAY['เปิดใช้งาน', 'ติดตั้ง', 'QR code']),
('ถ้าฉันต้องการความช่วยเหลือเกี่ยวกับ eSIM?', 'ทีมสนับสนุนของเราพร้อมให้บริการ 24/7 ผ่านแชท อีเมล หรือ LINE เราให้บริการทั้งภาษาไทยและอังกฤษเพื่อช่วยเหลือคุณกับทุกคำถามหรือปัญหา', 'faq', 'th', true, false, ARRAY['ช่วยเหลือ', 'สนับสนุน', '24/7']);