-- Insert Getting Started articles (English) - Core installation and setup guides

INSERT INTO kb_articles (title, slug, category, language, description, content, table_of_contents, source, is_published, is_internal, display_order)
VALUES 
-- 1. How to get an eSIM
('How can I get an eSIM?', 'how-to-get-an-esim', 'getting-started', 'en', 
'Step-by-step guide to purchasing your first eSIM from Mobile11',
E'# How can I get an eSIM?\n\nGetting an eSIM from Mobile11 is quick and easy. Follow these simple steps to purchase and start using your eSIM.\n\n## Step 1: Find Your Destination {#find-destination}\n\n1. Visit the Mobile11 website or open the Mobile11 app\n2. Use the search bar to find your travel destination\n3. You can search by country name or browse by region\n\n## Step 2: Choose Your Package {#choose-package}\n\n1. Browse available eSIM packages for your destination\n2. Compare data amounts, validity periods, and prices\n3. Mobile11 offers three package types:\n   - **Limitless**: Unlimited high-speed data\n   - **Max Speed**: Fixed data at maximum speeds\n   - **Day Pass**: Daily data allowance that resets each day\n\n## Step 3: Complete Your Purchase {#complete-purchase}\n\n1. Add your chosen package to cart\n2. Create an account or continue as guest\n3. Apply any promo codes for discounts\n4. Complete payment using your preferred method\n\n## Step 4: Receive Your eSIM {#receive-esim}\n\n1. Your eSIM details will be sent to your email\n2. You can also view them in My eSIMs section\n3. You''ll receive a QR code and activation details\n\n## Step 5: Install and Activate {#install-activate}\n\n1. Scan the QR code with your compatible device\n2. Follow the on-screen instructions\n3. Your eSIM is ready to use!\n\n**Tip:** You can install your eSIM before your trip, but data usage only begins when you connect to a network in your destination country.',
'[{"id":"find-destination","title":"Find Your Destination"},{"id":"choose-package","title":"Choose Your Package"},{"id":"complete-purchase","title":"Complete Your Purchase"},{"id":"receive-esim","title":"Receive Your eSIM"},{"id":"install-activate","title":"Install and Activate"}]'::jsonb,
'both', true, false, 1),

-- 2. Install eSIM on iOS (Complete)
('How to install eSIM on your iOS device', 'install-esim-ios', 'getting-started', 'en',
'Complete guide to installing Mobile11 eSIM on iPhone and iPad',
E'# How to install eSIM on your iOS device\n\nThis guide covers all methods to install your Mobile11 eSIM on iPhone or iPad. Choose the method that works best for you.\n\n## Before You Begin {#before-begin}\n\n**Requirements:**\n- iPhone XS or later (or iPad Pro 2018 or later)\n- iOS 12.1 or later\n- Device must be carrier unlocked\n- Stable internet connection (WiFi or mobile data)\n\n## Method 1: Install via QR Code {#qr-code}\n\nThis is the easiest and most common method:\n\n1. Go to **Settings** > **Cellular** (or **Mobile Data**)\n2. Tap **Add eSIM** or **Add Cellular Plan**\n3. Select **Use QR Code**\n4. Scan the QR code from your Mobile11 order email\n5. Tap **Continue** when prompted\n6. Choose a label for your eSIM (e.g., "Travel" or "Mobile11")\n7. Select **Use this line for Cellular Data Only**\n8. Tap **Done**\n\n## Method 2: Install Manually {#manual}\n\nIf you can''t scan the QR code:\n\n1. Go to **Settings** > **Cellular** > **Add eSIM**\n2. Tap **Use QR Code**, then **Enter Details Manually**\n3. Enter the **SM-DP+ Address** from your order\n4. Enter the **Activation Code**\n5. Tap **Next** and follow the prompts\n6. Complete the setup as described above\n\n## Method 3: Direct Install (App) {#direct}\n\nIf using the Mobile11 app:\n\n1. Open the Mobile11 app\n2. Go to **My eSIMs**\n3. Select your purchased eSIM\n4. Tap **Install eSIM**\n5. Follow the on-screen instructions\n\n## After Installation {#after-install}\n\nTo start using your eSIM:\n\n1. Go to **Settings** > **Cellular**\n2. Tap on your Mobile11 eSIM\n3. Toggle **Turn On This Line**\n4. Enable **Data Roaming**\n5. Set Mobile11 as your **Cellular Data** line\n\n## Troubleshooting {#troubleshooting}\n\n- **eSIM won''t install?** Check your internet connection and try again\n- **Error message?** Ensure your device is carrier unlocked\n- **No signal?** Enable Data Roaming in cellular settings',
'[{"id":"before-begin","title":"Before You Begin"},{"id":"qr-code","title":"Install via QR Code"},{"id":"manual","title":"Install Manually"},{"id":"direct","title":"Direct Install (App)"},{"id":"after-install","title":"After Installation"},{"id":"troubleshooting","title":"Troubleshooting"}]'::jsonb,
'both', true, false, 2),

-- 3. Install eSIM on Android
('How to install eSIM on your Android device', 'install-esim-android', 'getting-started', 'en',
'Complete guide to installing Mobile11 eSIM on Android phones',
E'# How to install eSIM on your Android device\n\nThis guide covers installing your Mobile11 eSIM on Android devices including Samsung Galaxy, Google Pixel, and other compatible phones.\n\n## Before You Begin {#before-begin}\n\n**Requirements:**\n- eSIM-compatible Android device\n- Android 9.0 or later\n- Device must be carrier unlocked\n- Stable internet connection\n\n**Note:** Menu names may vary slightly between manufacturers.\n\n## Method 1: Install via QR Code {#qr-code}\n\n### For Samsung Galaxy:\n1. Go to **Settings** > **Connections** > **SIM Manager**\n2. Tap **Add eSIM**\n3. Select **Scan QR code from service provider**\n4. Scan the QR code from your Mobile11 order\n5. Tap **Confirm** to add the plan\n6. Name your eSIM (e.g., "Mobile11 Travel")\n\n### For Google Pixel:\n1. Go to **Settings** > **Network & Internet** > **SIMs**\n2. Tap **Add** or the **+** icon\n3. Select **Download a SIM instead**\n4. Tap **Next** and scan the QR code\n5. Follow the prompts to complete setup\n\n## Method 2: Install Manually {#manual}\n\n1. Go to your device''s SIM/eSIM settings\n2. Choose to add an eSIM\n3. Select **Enter code manually** or **Enter activation code**\n4. Enter the **SM-DP+ Address** from your order\n5. Enter the **Activation Code**\n6. Tap **Add** or **Confirm**\n\n## After Installation {#after-install}\n\n1. Go to **Settings** > **Connections** > **SIM Manager**\n2. Tap on your Mobile11 eSIM\n3. Enable the eSIM\n4. Set it as the **Mobile data** SIM\n5. Enable **Data roaming** when prompted\n\n## Setting APN (If Required) {#apn-settings}\n\nMost eSIMs auto-configure, but if needed:\n\n1. Go to **Settings** > **Connections** > **Mobile networks**\n2. Select your Mobile11 eSIM\n3. Tap **Access Point Names**\n4. Add a new APN with details from your order email',
'[{"id":"before-begin","title":"Before You Begin"},{"id":"qr-code","title":"Install via QR Code"},{"id":"manual","title":"Install Manually"},{"id":"after-install","title":"After Installation"},{"id":"apn-settings","title":"Setting APN"}]'::jsonb,
'both', true, false, 3),

-- 4. Check iOS eSIM Compatibility
('How to check if your iOS device supports eSIM', 'check-ios-esim-compatibility', 'getting-started', 'en',
'Verify if your iPhone or iPad can use eSIM technology',
E'# How to check if your iOS device supports eSIM\n\nNot all iPhones and iPads support eSIM. Here''s how to check if your device is compatible.\n\n## Compatible iPhone Models {#compatible-iphones}\n\nThe following iPhones support eSIM:\n\n- iPhone XS, XS Max, XR (2018)\n- iPhone 11, 11 Pro, 11 Pro Max\n- iPhone SE (2nd generation, 2020)\n- iPhone 12 mini, 12, 12 Pro, 12 Pro Max\n- iPhone 13 mini, 13, 13 Pro, 13 Pro Max\n- iPhone SE (3rd generation, 2022)\n- iPhone 14, 14 Plus, 14 Pro, 14 Pro Max\n- iPhone 15, 15 Plus, 15 Pro, 15 Pro Max\n- All newer models\n\n## Compatible iPad Models {#compatible-ipads}\n\n- iPad Pro 11-inch (all generations)\n- iPad Pro 12.9-inch (3rd generation and later)\n- iPad Air (3rd generation and later)\n- iPad (7th generation and later)\n- iPad mini (5th generation and later)\n\n## How to Check on Your Device {#check-device}\n\n### Method 1: Check Settings\n1. Go to **Settings** > **Cellular** (or **Mobile Data**)\n2. If you see **Add eSIM** or **Add Cellular Plan**, your device supports eSIM\n\n### Method 2: Check IMEI Info\n1. Go to **Settings** > **General** > **About**\n2. Scroll down to find **Available SIM**\n3. If it shows a second IMEI or mentions eSIM, you''re compatible\n\n### Method 3: Dial Code\n1. Open the Phone app\n2. Dial **\\*#06#**\n3. If you see multiple IMEI numbers (including EID), your device supports eSIM\n\n## Important Notes {#important-notes}\n\n- Your device must be **carrier unlocked** to use a Mobile11 eSIM\n- Some carrier-locked devices may show eSIM options but won''t accept third-party eSIMs\n- Devices purchased in mainland China typically don''t support eSIM (except iPhone 15 series)',
'[{"id":"compatible-iphones","title":"Compatible iPhone Models"},{"id":"compatible-ipads","title":"Compatible iPad Models"},{"id":"check-device","title":"How to Check on Your Device"},{"id":"important-notes","title":"Important Notes"}]'::jsonb,
'both', true, false, 4),

-- 5. Check Android eSIM Compatibility
('How to check if your Android device supports eSIM', 'check-android-esim-compatibility', 'getting-started', 'en',
'Verify if your Android phone can use eSIM technology',
E'# How to check if your Android device supports eSIM\n\nMany Android phones now support eSIM, but compatibility varies. Here''s how to check.\n\n## Popular Compatible Devices {#compatible-devices}\n\n### Samsung Galaxy:\n- Galaxy S20, S21, S22, S23, S24 series\n- Galaxy Note 20 series\n- Galaxy Z Fold and Z Flip series\n- Galaxy A54, A55 and newer A-series models\n\n### Google Pixel:\n- Pixel 2 and all newer models\n- Pixel 6, 7, 8, 9 series\n- Pixel Fold\n\n### Other Brands:\n- OnePlus (select models)\n- Xiaomi (select models)\n- OPPO (select models)\n- Motorola (select models)\n\n## How to Check on Your Device {#check-device}\n\n### Method 1: Check Settings\n1. Go to **Settings** > **Connections** (or **Network & Internet**)\n2. Look for **SIM Manager** or **SIMs**\n3. If you see **Add eSIM** option, your device is compatible\n\n### Method 2: Dial Code\n1. Open the Phone app\n2. Dial **\\*#06#**\n3. Look for an **EID** number\n4. If EID is present, your device supports eSIM\n\n### Method 3: Check with Manufacturer\n1. Visit your phone manufacturer''s website\n2. Search for your exact model number\n3. Check the specifications for eSIM support\n\n## Important Requirements {#requirements}\n\n- **Carrier unlocked**: Your device must not be locked to a specific carrier\n- **Latest software**: Update to the newest Android version available\n- **Region**: Some regional variants may not have eSIM enabled\n\n## Note for Dual SIM Users {#dual-sim}\n\nMany Android phones support:\n- 1 physical SIM + 1 eSIM\n- 2 eSIMs (newer models)\n\nCheck your device specifications for the exact configuration supported.',
'[{"id":"compatible-devices","title":"Popular Compatible Devices"},{"id":"check-device","title":"How to Check on Your Device"},{"id":"requirements","title":"Important Requirements"},{"id":"dual-sim","title":"Note for Dual SIM Users"}]'::jsonb,
'both', true, false, 5),

-- 6. When can I use my eSIM
('When can I use my eSIM?', 'when-can-i-use-my-esim', 'getting-started', 'en',
'Learn when your eSIM activates and starts working',
E'# When can I use my eSIM?\n\nUnderstanding when your eSIM becomes active is important for planning your trip.\n\n## Installation vs Activation {#install-vs-activate}\n\n**Installation**: You can install your eSIM immediately after purchase, even before your trip.\n\n**Activation**: Your eSIM data package begins when:\n- You connect to a supported network in your destination country\n- The validity period starts counting down\n\n## Pre-Trip Installation (Recommended) {#pre-trip}\n\nWe recommend installing your eSIM before you travel:\n\n1. **Install at home** while connected to WiFi\n2. **Don''t enable data roaming** until you arrive\n3. **Turn on the eSIM** when you land at your destination\n4. **Enable data roaming** to start using data\n\n## Validity Period {#validity}\n\nYour eSIM package validity starts when:\n- For most packages: First connection to a local network\n- For some packages: Immediately upon activation (check package details)\n\n**Example**: A 7-day package starts counting when you first connect in your destination country, not when you purchase or install.\n\n## Best Practices {#best-practices}\n\n1. **Purchase** your eSIM 1-7 days before your trip\n2. **Install** the eSIM before leaving (stable WiFi at home)\n3. **Keep data roaming OFF** until arrival\n4. **Enable data roaming** when you land\n5. Your data package begins!\n\n## Multiple Destinations {#multiple-destinations}\n\nIf visiting multiple countries:\n- Use a **Regional** or **Global** eSIM for seamless coverage\n- Or purchase separate local eSIMs for each country\n- Your device can store multiple eSIMs (switch between them as needed)',
'[{"id":"install-vs-activate","title":"Installation vs Activation"},{"id":"pre-trip","title":"Pre-Trip Installation"},{"id":"validity","title":"Validity Period"},{"id":"best-practices","title":"Best Practices"},{"id":"multiple-destinations","title":"Multiple Destinations"}]'::jsonb,
'both', true, false, 6),

-- 7. When should I buy my eSIM
('When should I buy my eSIM?', 'when-to-buy-esim', 'getting-started', 'en',
'Timing recommendations for purchasing your travel eSIM',
E'# When should I buy my eSIM?\n\nTiming your eSIM purchase correctly ensures a smooth travel experience.\n\n## Recommended Timeline {#timeline}\n\n### Best Practice: 1-7 Days Before Travel\n- Gives you time to install and verify everything works\n- No rush or stress at the airport\n- Time to contact support if any issues\n\n### Acceptable: Day of Travel\n- Purchase and install at the airport\n- Requires stable WiFi connection\n- Less time to troubleshoot if problems occur\n\n### Last Minute: Upon Arrival\n- Purchase when you land\n- May need to find WiFi first\n- Not ideal for those who need data immediately\n\n## Why Buy in Advance? {#why-advance}\n\n1. **Install at home** with reliable WiFi\n2. **Test the installation** before you travel\n3. **Get support** if you encounter issues\n4. **No stress** at the airport or arrival\n5. **Immediate connectivity** when you land\n\n## Important Notes {#notes}\n\n- Your data package validity does **NOT** start until you use it\n- You can install the eSIM in advance without starting the validity period\n- Just keep data roaming OFF until you arrive at your destination\n\n## Package Availability {#availability}\n\nSome popular destinations may occasionally have limited stock. Buying in advance ensures:\n- Your preferred package is available\n- You get the best prices (flash sales, promo codes)\n- No last-minute surprises',
'[{"id":"timeline","title":"Recommended Timeline"},{"id":"why-advance","title":"Why Buy in Advance?"},{"id":"notes","title":"Important Notes"},{"id":"availability","title":"Package Availability"}]'::jsonb,
'both', true, false, 7),

-- 8. When does eSIM expire
('When does my eSIM data package expire?', 'when-does-esim-expire', 'getting-started', 'en',
'Understanding eSIM validity periods and expiration',
E'# When does my eSIM data package expire?\n\nUnderstanding validity periods helps you maximize your eSIM usage.\n\n## How Validity Works {#how-it-works}\n\nMobile11 eSIM packages have two limits:\n1. **Data amount**: Total GB/MB included\n2. **Validity period**: Number of days the package is active\n\nYour package expires when **either** limit is reached (whichever comes first).\n\n## When Does Validity Start? {#when-starts}\n\n### For Most Packages:\n- Validity starts when you **first connect** to a network in your destination\n- Simply installing the eSIM does NOT start the countdown\n- Enable data roaming to begin using the package\n\n### Special Cases:\n- Some packages start immediately upon activation\n- Check the specific package details before purchasing\n\n## Example Scenarios {#examples}\n\n**Scenario 1**: 5GB, 7-day package\n- If you use all 5GB in 3 days → Package ends (no more data)\n- If 7 days pass with 2GB remaining → Package ends (time expired)\n\n**Scenario 2**: Day Pass packages\n- Daily data resets at midnight (local time or UTC, check details)\n- Valid for the specified number of days\n\n## Extending Your Package {#extending}\n\nIf you need more data or time:\n1. **Top Up**: Some packages support top-ups (check "Top Up" option)\n2. **Buy New**: Purchase an additional package if needed\n3. **Renewals**: Use auto-renewal feature for uninterrupted service\n\n## Checking Remaining Validity {#check-remaining}\n\n1. Log into your Mobile11 account\n2. Go to **My eSIMs**\n3. View remaining data and days\n4. Or use iOS widgets (if available)',
'[{"id":"how-it-works","title":"How Validity Works"},{"id":"when-starts","title":"When Does Validity Start?"},{"id":"examples","title":"Example Scenarios"},{"id":"extending","title":"Extending Your Package"},{"id":"check-remaining","title":"Checking Remaining Validity"}]'::jsonb,
'both', true, false, 8),

-- 9. How to change APN settings
('How to change your APN settings', 'how-to-change-apn-settings', 'getting-started', 'en',
'Configure Access Point Name settings for your eSIM',
E'# How to change your APN settings\n\nMost Mobile11 eSIMs configure automatically, but sometimes you may need to set the APN manually.\n\n## What is APN? {#what-is-apn}\n\nAPN (Access Point Name) is the gateway between your device and the mobile network. Correct APN settings are required for:\n- Mobile data connection\n- MMS messaging (if supported)\n- Internet browsing\n\n## When to Change APN {#when-to-change}\n\nYou may need to configure APN if:\n- Your eSIM is installed but data isn''t working\n- You see "No Internet Connection" with signal bars\n- The package details specify manual APN setup\n\n## APN Settings on iOS {#ios-apn}\n\n1. Go to **Settings** > **Cellular** (or **Mobile Data**)\n2. Tap on your Mobile11 eSIM plan\n3. Tap **Cellular Data Network**\n4. Under **Cellular Data**, enter:\n   - **APN**: (from your order email)\n   - Leave username and password blank unless specified\n5. Scroll down to **LTE Setup** (if available)\n6. Enter the same APN\n7. Go back and restart your device\n\n## APN Settings on Android {#android-apn}\n\n1. Go to **Settings** > **Connections** > **Mobile Networks**\n2. Select your Mobile11 eSIM\n3. Tap **Access Point Names**\n4. Tap the **+** icon to add a new APN\n5. Enter:\n   - **Name**: Mobile11\n   - **APN**: (from your order email)\n6. Tap the three dots menu > **Save**\n7. Select the new APN\n8. Restart your device\n\n## Common APN Values {#common-values}\n\nMost Mobile11 eSIMs use:\n- **APN**: internet or data\n- **No username/password** required\n\nCheck your order confirmation email for specific values.\n\n## Still Not Working? {#troubleshooting}\n\n1. Restart your device after changing APN\n2. Ensure data roaming is enabled\n3. Try resetting network settings as last resort\n4. Contact Mobile11 support with your order number',
'[{"id":"what-is-apn","title":"What is APN?"},{"id":"when-to-change","title":"When to Change APN"},{"id":"ios-apn","title":"APN Settings on iOS"},{"id":"android-apn","title":"APN Settings on Android"},{"id":"common-values","title":"Common APN Values"},{"id":"troubleshooting","title":"Still Not Working?"}]'::jsonb,
'both', true, false, 9),

-- 10. Payment methods
('What payment methods are accepted?', 'payment-methods-accepted', 'getting-started', 'en',
'All accepted payment options for purchasing eSIMs',
E'# What payment methods are accepted?\n\nMobile11 offers multiple secure payment options for your convenience.\n\n## Credit & Debit Cards {#cards}\n\nWe accept major credit and debit cards:\n- Visa\n- Mastercard\n- American Express\n- JCB\n- UnionPay\n\n## Digital Wallets {#wallets}\n\n- Apple Pay\n- Google Pay\n- PayPal\n\n## Local Payment Methods {#local}\n\nDepending on your region:\n- PromptPay (Thailand)\n- TrueMoney Wallet (Thailand)\n- Other regional options\n\n## Mobile11 Money {#mobile11-money}\n\nUse your Mobile11 Money balance:\n- Earned from cashback rewards\n- From referral bonuses\n- Applied at checkout\n\nMinimum order value of $1 USD required to use Mobile11 Money.\n\n## Payment Security {#security}\n\n- All transactions are encrypted with SSL/TLS\n- We don''t store your full card details\n- 3D Secure authentication for eligible cards\n- PCI DSS compliant payment processing\n\n## Currency {#currency}\n\n- Prices shown in your selected currency\n- Supported currencies: USD, EUR, GBP, THB, and more\n- Exchange rates updated regularly\n- No hidden conversion fees from Mobile11\n\n## Payment Issues? {#issues}\n\nIf your payment fails:\n1. Check your card has sufficient funds\n2. Verify card details are correct\n3. Try a different payment method\n4. Contact your bank if blocks persist\n5. Reach out to Mobile11 support',
'[{"id":"cards","title":"Credit & Debit Cards"},{"id":"wallets","title":"Digital Wallets"},{"id":"local","title":"Local Payment Methods"},{"id":"mobile11-money","title":"Mobile11 Money"},{"id":"security","title":"Payment Security"},{"id":"currency","title":"Currency"},{"id":"issues","title":"Payment Issues?"}]'::jsonb,
'both', true, false, 10);

-- Also insert Thai translations for Getting Started
INSERT INTO kb_articles (title, slug, category, language, description, content, table_of_contents, source, is_published, is_internal, display_order)
VALUES 
('ฉันจะซื้อ eSIM ได้อย่างไร?', 'how-to-get-an-esim', 'getting-started', 'th',
'คู่มือขั้นตอนการซื้อ eSIM จาก Mobile11',
E'# ฉันจะซื้อ eSIM ได้อย่างไร?\n\nการซื้อ eSIM จาก Mobile11 นั้นง่ายและรวดเร็ว ทำตามขั้นตอนง่ายๆ เหล่านี้\n\n## ขั้นตอนที่ 1: ค้นหาจุดหมายปลายทาง {#find-destination}\n\n1. เยี่ยมชมเว็บไซต์ Mobile11 หรือเปิดแอป\n2. ใช้แถบค้นหาเพื่อหาปลายทางของคุณ\n3. สามารถค้นหาตามชื่อประเทศหรือดูตามภูมิภาค\n\n## ขั้นตอนที่ 2: เลือกแพ็กเกจ {#choose-package}\n\n1. ดูแพ็กเกจ eSIM ที่มีสำหรับปลายทางของคุณ\n2. เปรียบเทียบปริมาณข้อมูล ระยะเวลา และราคา\n3. Mobile11 มี 3 ประเภทแพ็กเกจ:\n   - **Limitless**: เน็ตไม่อั้นความเร็วสูง\n   - **Max Speed**: ข้อมูลจำกัดความเร็วสูงสุด\n   - **Day Pass**: เน็ตรายวันรีเซ็ตทุกวัน\n\n## ขั้นตอนที่ 3: ชำระเงิน {#complete-purchase}\n\n1. เพิ่มแพ็กเกจลงตะกร้า\n2. สร้างบัญชีหรือซื้อแบบ Guest\n3. ใส่โค้ดส่วนลดถ้ามี\n4. ชำระเงินด้วยวิธีที่สะดวก\n\n## ขั้นตอนที่ 4: รับ eSIM {#receive-esim}\n\n1. รายละเอียด eSIM จะส่งไปทางอีเมล\n2. ดูได้ในส่วน eSIM ของฉัน\n3. คุณจะได้รับ QR code และรหัสเปิดใช้งาน\n\n## ขั้นตอนที่ 5: ติดตั้งและเปิดใช้งาน {#install-activate}\n\n1. สแกน QR code ด้วยอุปกรณ์ที่รองรับ\n2. ทำตามคำแนะนำบนหน้าจอ\n3. eSIM พร้อมใช้งาน!',
'[{"id":"find-destination","title":"ค้นหาจุดหมายปลายทาง"},{"id":"choose-package","title":"เลือกแพ็กเกจ"},{"id":"complete-purchase","title":"ชำระเงิน"},{"id":"receive-esim","title":"รับ eSIM"},{"id":"install-activate","title":"ติดตั้งและเปิดใช้งาน"}]'::jsonb,
'both', true, false, 1),

('วิธีติดตั้ง eSIM บน iOS', 'install-esim-ios', 'getting-started', 'th',
'คู่มือติดตั้ง Mobile11 eSIM บน iPhone และ iPad',
E'# วิธีติดตั้ง eSIM บน iOS\n\nคู่มือนี้ครอบคลุมทุกวิธีการติดตั้ง eSIM บน iPhone หรือ iPad\n\n## ก่อนเริ่มต้น {#before-begin}\n\n**ข้อกำหนด:**\n- iPhone XS ขึ้นไป (หรือ iPad Pro 2018 ขึ้นไป)\n- iOS 12.1 ขึ้นไป\n- เครื่องต้องปลดล็อคค่าย\n- การเชื่อมต่ออินเทอร์เน็ตที่เสถียร\n\n## วิธีที่ 1: ติดตั้งผ่าน QR Code {#qr-code}\n\n1. ไปที่ **ตั้งค่า** > **เซลลูลาร์**\n2. แตะ **เพิ่ม eSIM**\n3. เลือก **ใช้ QR Code**\n4. สแกน QR code จากอีเมลคำสั่งซื้อ\n5. แตะ **ดำเนินการต่อ**\n6. เลือกชื่อสำหรับ eSIM (เช่น "ท่องเที่ยว")\n7. เลือก **ใช้สายนี้สำหรับข้อมูลเซลลูลาร์เท่านั้น**\n\n## วิธีที่ 2: ติดตั้งด้วยตนเอง {#manual}\n\n1. ไปที่ **ตั้งค่า** > **เซลลูลาร์** > **เพิ่ม eSIM**\n2. แตะ **ใช้ QR Code** จากนั้น **ป้อนรายละเอียดด้วยตนเอง**\n3. ป้อน **ที่อยู่ SM-DP+** จากคำสั่งซื้อ\n4. ป้อน **รหัสเปิดใช้งาน**\n5. แตะ **ถัดไป** และทำตามคำแนะนำ\n\n## หลังติดตั้ง {#after-install}\n\n1. ไปที่ **ตั้งค่า** > **เซลลูลาร์**\n2. แตะ eSIM ของ Mobile11\n3. เปิด **เปิดใช้สายนี้**\n4. เปิด **ข้อมูลโรมมิ่ง**\n5. ตั้ง Mobile11 เป็นสายข้อมูล',
'[{"id":"before-begin","title":"ก่อนเริ่มต้น"},{"id":"qr-code","title":"ติดตั้งผ่าน QR Code"},{"id":"manual","title":"ติดตั้งด้วยตนเอง"},{"id":"after-install","title":"หลังติดตั้ง"}]'::jsonb,
'both', true, false, 2),

('วิธีติดตั้ง eSIM บน Android', 'install-esim-android', 'getting-started', 'th',
'คู่มือติดตั้ง Mobile11 eSIM บนมือถือ Android',
E'# วิธีติดตั้ง eSIM บน Android\n\nคู่มือนี้ครอบคลุมการติดตั้ง eSIM บนอุปกรณ์ Android รวมถึง Samsung Galaxy, Google Pixel และอื่นๆ\n\n## ก่อนเริ่มต้น {#before-begin}\n\n**ข้อกำหนด:**\n- อุปกรณ์ Android ที่รองรับ eSIM\n- Android 9.0 ขึ้นไป\n- เครื่องต้องปลดล็อคค่าย\n- การเชื่อมต่ออินเทอร์เน็ตที่เสถียร\n\n## วิธีที่ 1: ติดตั้งผ่าน QR Code {#qr-code}\n\n### สำหรับ Samsung Galaxy:\n1. ไปที่ **ตั้งค่า** > **การเชื่อมต่อ** > **ตัวจัดการ SIM**\n2. แตะ **เพิ่ม eSIM**\n3. เลือก **สแกน QR code จากผู้ให้บริการ**\n4. สแกน QR code จากคำสั่งซื้อ\n5. แตะ **ยืนยัน**\n\n### สำหรับ Google Pixel:\n1. ไปที่ **ตั้งค่า** > **เครือข่ายและอินเทอร์เน็ต** > **SIM**\n2. แตะ **เพิ่ม** หรือไอคอน **+**\n3. เลือก **ดาวน์โหลด SIM แทน**\n4. แตะ **ถัดไป** และสแกน QR code\n\n## วิธีที่ 2: ติดตั้งด้วยตนเอง {#manual}\n\n1. ไปที่การตั้งค่า SIM/eSIM\n2. เลือกเพิ่ม eSIM\n3. เลือก **ป้อนรหัสด้วยตนเอง**\n4. ป้อน **ที่อยู่ SM-DP+**\n5. ป้อน **รหัสเปิดใช้งาน**\n6. แตะ **เพิ่ม**\n\n## หลังติดตั้ง {#after-install}\n\n1. ไปที่ **ตั้งค่า** > **การเชื่อมต่อ** > **ตัวจัดการ SIM**\n2. แตะ eSIM ของ Mobile11\n3. เปิดใช้งาน eSIM\n4. ตั้งเป็น SIM สำหรับข้อมูลมือถือ\n5. เปิด **ข้อมูลโรมมิ่ง**',
'[{"id":"before-begin","title":"ก่อนเริ่มต้น"},{"id":"qr-code","title":"ติดตั้งผ่าน QR Code"},{"id":"manual","title":"ติดตั้งด้วยตนเอง"},{"id":"after-install","title":"หลังติดตั้ง"}]'::jsonb,
'both', true, false, 3);